using System.ComponentModel.DataAnnotations; using System.ComponentModel.DataAnnotations.Schema;
namespace SystemScope.Api;
public abstract class Record{[Key]public Guid Id{get;set;}=Guid.NewGuid();public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public DateTimeOffset UpdatedAt{get;set;}=DateTimeOffset.UtcNow;[Timestamp]public byte[]? RowVersion{get;set;}public bool Archived{get;set;}}
public class Project:Record{public string Name{get;set;}="";public string Objective{get;set;}="";public string Scope{get;set;}="";public string Owner{get;set;}="";public DateOnly StartDate{get;set;}public DateOnly TargetDate{get;set;}public ProjectStatus Status{get;set;}=ProjectStatus.Active;public List<AssessedSystem> Systems{get;set;}=[];}
public class AssessedSystem:Record{public Guid ProjectId{get;set;}public string Name{get;set;}="";public string Acronym{get;set;}="";public string Description{get;set;}="";public string BusinessOwner{get;set;}="";public string TechnicalOwner{get;set;}="";public Criticality Criticality{get;set;}public string Lifecycle{get;set;}="Active";public List<Integration> Integrations{get;set;}=[];}
public class Integration:Record{public Guid ProjectId{get;set;}public Guid SystemId{get;set;}public string Name{get;set;}="";public string Target{get;set;}="";public string Method{get;set;}="API";public string Owner{get;set;}="";public string Monitoring{get;set;}="";}
public class AssessmentTemplate:Record{public string Name{get;set;}="";public int Version{get;set;}=1;public bool Published{get;set;}=true;public List<TemplateSection> Sections{get;set;}=[];}
public class TemplateSection:Record{public Guid AssessmentTemplateId{get;set;}public string Name{get;set;}="";public int Order{get;set;}public List<Question> Questions{get;set;}=[];}
public class Question:Record{public Guid TemplateSectionId{get;set;}public string Text{get;set;}="";public QuestionType Type{get;set;}=QuestionType.Text;public bool Mandatory{get;set;}=true;public int Order{get;set;}}
public class Assessment:Record{public Guid ProjectId{get;set;}public Guid SystemId{get;set;}public AssessedSystem System{get;set;}=null!;public Guid TemplateId{get;set;}public AssessmentTemplate Template{get;set;}=null!;public int TemplateVersion{get;set;}public AssessmentStatus Status{get;set;}public string? Reviewer{get;set;}public string? ReviewComment{get;set;}public List<AssessmentResponse> Responses{get;set;}=[];}
public class AssessmentResponse:Record{public Guid ProjectId{get;set;}public Guid AssessmentId{get;set;}public Guid QuestionId{get;set;}public Question Question{get;set;}=null!;public string? Answer{get;set;}public string? Comment{get;set;}public ResponseConfidence Confidence{get;set;}=ResponseConfidence.Unconfirmed;public ResponseStatus Status{get;set;}=ResponseStatus.Draft;public string? Respondent{get;set;}public string? Reviewer{get;set;}public List<ResponseEvidence> EvidenceLinks{get;set;}=[];}
public class Evidence:Record{public Guid ProjectId{get;set;}public Guid? SystemId{get;set;}public string Title{get;set;}="";public string Url{get;set;}="";public string Source{get;set;}="";public string Classification{get;set;}="OFFICIAL";public bool Validated{get;set;}}
public class ResponseEvidence{public Guid AssessmentResponseId{get;set;}public AssessmentResponse AssessmentResponse{get;set;}=null!;public Guid EvidenceId{get;set;}public Evidence Evidence{get;set;}=null!;}
public class Finding:Record{public Guid ProjectId{get;set;}public Guid SystemId{get;set;}public Guid? AssessmentResponseId{get;set;}public Guid? EvidenceId{get;set;}public FindingType Type{get;set;}public string Title{get;set;}="";public string Description{get;set;}="";public Severity Severity{get;set;}public int Likelihood{get;set;}=1;public int Impact{get;set;}=1;public int? RiskOverride{get;set;}public string? RiskOverrideRationale{get;set;}[NotMapped]public int RiskScore=>RiskOverride??Likelihood*Impact;public string Owner{get;set;}="";public string? EvidenceGapRationale{get;set;}public ReviewState ReviewState{get;set;}=ReviewState.Draft;public string? ReviewComment{get;set;}}
public class Requirement:Record{public Guid ProjectId{get;set;}public string Title{get;set;}="";public string Description{get;set;}="";public string Type{get;set;}="Technical";public string Category{get;set;}="Technical";public Priority Priority{get;set;}public bool Mandatory{get;set;}=true;public string Rationale{get;set;}="";public string AcceptanceCriteria{get;set;}="";public string? StandaloneRationale{get;set;}public ReviewState ApprovalState{get;set;}=ReviewState.Draft;public string? SubmittedBy{get;set;}public string? ReviewComment{get;set;}public List<RequirementFinding> FindingLinks{get;set;}=[];}
public class RequirementFinding{public Guid RequirementId{get;set;}public Requirement Requirement{get;set;}=null!;public Guid FindingId{get;set;}public Finding Finding{get;set;}=null!;}
public class AssessmentAction:Record{public Guid ProjectId{get;set;}public Guid? SystemId{get;set;}public string Title{get;set;}="";public string Owner{get;set;}="";public DateOnly DueDate{get;set;}public Priority Priority{get;set;}public ActionStatus Status{get;set;}=ActionStatus.Open;}
public class AuditEvent{[Key]public Guid Id{get;set;}=Guid.NewGuid();public Guid? ProjectId{get;set;}public string ActorId{get;set;}="";public string ActorName{get;set;}="";public string Action{get;set;}="";public string EntityType{get;set;}="";public Guid EntityId{get;set;}public string Detail{get;set;}="";public DateTimeOffset Timestamp{get;set;}=DateTimeOffset.UtcNow;}
public class LandscapeSnapshot:Record{public string Version{get;set;}="v5.0";public string Layer{get;set;}="AsIs";public string Title{get;set;}="";public string ConfirmedBy{get;set;}="";public DateTimeOffset? ConfirmedAt{get;set;}public string ChangeNote{get;set;}="";public string Document{get;set;}="{}";}
public enum ProjectStatus{Draft,Active,OnHold,Complete,Archived}public enum Criticality{Low,Moderate,High,Critical}public enum QuestionType{Text,RichText,YesNoUnknown,SingleChoice,MultipleChoice,Number,Date,Rating,Link,Relationship}public enum AssessmentStatus{NotStarted,InProgress,Submitted,Approved,Returned,Complete}public enum ResponseConfidence{ConfirmedByEvidence,ConfirmedBySme,Inferred,Unconfirmed}public enum ResponseStatus{Draft,Answered,FollowUp,Unconfirmed,Unknown,NotApplicable}public enum FindingType{Observation,Issue,Risk,Constraint,Dependency,TechnicalDebt,Recommendation,InformationGap}public enum Severity{Low=1,Moderate=2,High=3,Critical=4}public enum ReviewState{Draft,Submitted,Approved,Returned}public enum Priority{Could,Should,Must}public enum ActionStatus{Open,InProgress,Blocked,Completed}
