using System.Security.Claims;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using SystemScope.Api;

var builder = WebApplication.CreateBuilder(args);
builder.Services.ConfigureHttpJsonOptions(o => o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.AddSystemScopeDataStore();
builder.Services.AddScoped<AppAccessService>();
var entra = builder.Configuration.GetSection("EntraId");
var tenant = entra["TenantId"] ?? builder.Configuration["AzureAd:TenantId"];
var apiClient = entra["ApiClientId"] ?? builder.Configuration["AzureAd:ClientId"];
var audience = entra["Audience"];
if (!string.IsNullOrWhiteSpace(tenant) && !string.IsNullOrWhiteSpace(apiClient))
{
    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o =>
    {
        o.Authority = $"https://login.microsoftonline.com/{tenant}/v2.0";
        o.Audience = apiClient;
        o.TokenValidationParameters.ValidAudiences = string.IsNullOrWhiteSpace(audience)
            ? [apiClient, $"api://{apiClient}"]
            : [apiClient, $"api://{apiClient}", audience];
        o.TokenValidationParameters.NameClaimType = "name";
        o.TokenValidationParameters.RoleClaimType = "roles";
        o.MapInboundClaims = false;
    });
}
else builder.Services.AddAuthentication("Development").AddScheme<Microsoft.AspNetCore.Authentication.AuthenticationSchemeOptions,DevelopmentAuthHandler>("Development",_=>{});
builder.Services.AddAuthorization(); builder.Services.AddProblemDetails(); builder.Services.AddScoped<AuditService>();
var app=builder.Build(); app.UseExceptionHandler(); app.UseDefaultFiles(); app.UseStaticFiles(); app.UseAuthentication(); app.UseApplicationAccessGate(); app.UseAuthorization();
{
    var factory = app.Services.GetRequiredService<IAzureSqlConnectionFactory>();
    var explicitSql = app.Configuration.GetConnectionString("SystemScope");
    if (!string.IsNullOrWhiteSpace(explicitSql))
        app.Logger.LogInformation("SystemScope is using ConnectionStrings:SystemScope.");
    else if (factory.IsConfigured)
        app.Logger.LogInformation("SystemScope is using Azure SQL {Server}/{Database} ({AuthenticationMode}). Schema is applied from database/migrations.", factory.Server, factory.Database, factory.AuthenticationMode);
    else
        app.Logger.LogInformation("SystemScope is using the in-memory database. Configure AzureSql to persist to Azure SQL.");
}
app.MapAccess();
var api=app.MapGroup("/api").RequireAuthorization();
api.MapScan();
api.MapCatalog();
api.MapWorkflow();
api.MapDemoViews();
api.MapLearning();
app.MapGet("/health", () => Results.Ok(new { status = "Healthy" }));
api.MapGet("/me",(ClaimsPrincipal u)=>new{name=u.Identity?.Name??"Local Assessor",roles=u.FindAll(ClaimTypes.Role).Select(x=>x.Value)});
api.MapGet("/dashboard",async(Guid? projectId,AppDbContext db)=>await ScanApi.Dashboard(db,projectId));
api.MapGet("/projects",async(AppDbContext db)=>await db.Projects.Include(x=>x.Systems).OrderByDescending(x=>x.UpdatedAt).ToListAsync());
api.MapPost("/projects",async(ProjectInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var p=new Project{Name=i.Name.Trim(),Objective=i.Objective.Trim(),Scope=i.Scope.Trim(),Owner=i.Owner.Trim(),StartDate=i.StartDate,TargetDate=i.TargetDate};db.Projects.Add(p);await audit.Record(db,u,"Create","Project",p.Id,p.Name,p.Id);await db.SaveChangesAsync();return Results.Created($"/api/projects/{p.Id}",p);});
api.MapGet("/projects/{id:guid}",async(Guid id,AppDbContext db)=>await db.Projects.Include(x=>x.Systems).FirstOrDefaultAsync(x=>x.Id==id) is{}p?Results.Ok(p):Results.NotFound());
api.MapPost("/projects/{id:guid}/systems",async(Guid id,SystemInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{if(!await db.Projects.AnyAsync(x=>x.Id==id))return Results.NotFound();var key=string.IsNullOrWhiteSpace(i.CatalogKey)?ScanWorkspace.Slug(i.Acronym,i.Name):i.CatalogKey.Trim().ToLowerInvariant();var master=await db.MasterSystems.FirstOrDefaultAsync(x=>x.CatalogKey==key||(x.Name==i.Name.Trim()&&x.Acronym==i.Acronym.Trim()));if(master is null){master=new MasterSystem{Name=i.Name.Trim(),Acronym=i.Acronym.Trim(),CatalogKey=key,Description=i.Description.Trim(),BusinessPurpose=(i.BusinessPurpose??"").Trim(),BusinessOwner=i.BusinessOwner.Trim(),TechnicalOwner=i.TechnicalOwner.Trim(),SupportTeam=(i.SupportTeam??"").Trim(),Vendor=(i.Vendor??"").Trim(),Product=(i.Product??"").Trim(),Tags=(i.Tags??"").Trim(),DataClassification=string.IsNullOrWhiteSpace(i.DataClassification)?"OFFICIAL":i.DataClassification.Trim(),Criticality=i.Criticality,LifecycleStatus=i.Lifecycle};db.MasterSystems.Add(master);}var s=new AssessedSystem{ProjectId=id,MasterSystemId=master.Id,CatalogKey=master.CatalogKey,Name=i.Name.Trim(),Acronym=i.Acronym.Trim(),Description=i.Description.Trim(),BusinessPurpose=(i.BusinessPurpose??"").Trim(),BusinessOwner=i.BusinessOwner.Trim(),TechnicalOwner=i.TechnicalOwner.Trim(),SupportTeam=(i.SupportTeam??"").Trim(),Vendor=(i.Vendor??"").Trim(),Product=(i.Product??"").Trim(),Tags=(i.Tags??"").Trim(),DataClassification=string.IsNullOrWhiteSpace(i.DataClassification)?"OFFICIAL":i.DataClassification.Trim(),Criticality=i.Criticality,Lifecycle=i.Lifecycle};db.Systems.Add(s);await db.SaveChangesAsync();await ScanWorkspace.Ensure(db,s);await audit.Record(db,u,"Create","System",s.Id,s.Name,id);await db.SaveChangesAsync();return Results.Created($"/api/systems/{s.Id}",s);});
api.MapGet("/systems/{id:guid}",async(Guid id,AppDbContext db)=>await db.Systems.Include(x=>x.Integrations).FirstOrDefaultAsync(x=>x.Id==id) is{}s?Results.Ok(s):Results.NotFound());
api.MapGet("/templates",async(AppDbContext db)=>await db.Templates.Include(x=>x.Sections.OrderBy(s=>s.Order)).ThenInclude(x=>x.Questions.OrderBy(q=>q.Order)).ToListAsync());
api.MapPost("/templates",async(TemplateInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{if(string.IsNullOrWhiteSpace(i.Name)||i.Sections.Count==0)return Results.ValidationProblem(new Dictionary<string,string[]>{{"template",["A name and at least one section are required."]}});var previous=await db.Templates.Where(x=>x.Name==i.Name).MaxAsync(x=>(int?)x.Version)??0;var t=new AssessmentTemplate{Name=i.Name.Trim(),Version=previous+1,Published=true,Sections=i.Sections.OrderBy(x=>x.Order).Select(s=>new TemplateSection{Name=s.Name.Trim(),Order=s.Order,Questions=s.Questions.OrderBy(x=>x.Order).Select(q=>new Question{Text=q.Text.Trim(),Type=q.Type,Mandatory=q.Mandatory,Order=q.Order}).ToList()}).ToList()};db.Templates.Add(t);await audit.Record(db,u,"Create","AssessmentTemplate",t.Id,$"{t.Name} v{t.Version}");await db.SaveChangesAsync();return Results.Created($"/api/templates/{t.Id}",t);});
api.MapPost("/systems/{id:guid}/assessments",async(Guid id,StartAssessment i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var s=await db.Systems.FindAsync(id);var t=await db.Templates.Include(x=>x.Sections).ThenInclude(x=>x.Questions).FirstOrDefaultAsync(x=>x.Id==i.TemplateId);if(s is null||t is null)return Results.NotFound();var a=new Assessment{ProjectId=s.ProjectId,SystemId=id,TemplateId=t.Id,TemplateVersion=t.Version,Status=AssessmentStatus.InProgress};foreach(var q in t.Sections.SelectMany(x=>x.Questions))a.Responses.Add(new AssessmentResponse{ProjectId=s.ProjectId,QuestionId=q.Id});db.Assessments.Add(a);await audit.Record(db,u,"Create","Assessment",a.Id,s.Name,s.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/assessments/{a.Id}",new{a.Id});});
api.MapGet("/assessments/{id:guid}",async(Guid id,AppDbContext db)=>await db.Assessments.Include(x=>x.System).Include(x=>x.Template).ThenInclude(x=>x.Sections.OrderBy(s=>s.Order)).ThenInclude(x=>x.Questions.OrderBy(q=>q.Order)).Include(x=>x.Responses).FirstOrDefaultAsync(x=>x.Id==id) is{}a?Results.Ok(a):Results.NotFound());
api.MapPut("/responses/{id:guid}",async(Guid id,ResponseInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var r=await db.Responses.FindAsync(id);if(r is null)return Results.NotFound();r.Answer=i.Answer?.Trim();r.Comment=i.Comment?.Trim();r.Confidence=i.Confidence;r.Status=i.Status;r.Respondent=u.Identity?.Name;await audit.Record(db,u,"Update","Response",id,r.Status.ToString(),r.ProjectId);await db.SaveChangesAsync();return Results.Ok(r);});
api.MapPut("/assessments/{id:guid}/review",async(Guid id,ReviewInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var a=await db.Assessments.Include(x=>x.Responses).ThenInclude(x=>x.Question).FirstOrDefaultAsync(x=>x.Id==id);if(a is null)return Results.NotFound();if(i.State==ReviewState.Submitted||i.State==ReviewState.Approved){var incomplete=a.Responses.Where(x=>x.Question.Mandatory&&string.IsNullOrWhiteSpace(x.Answer)&&x.Status is not ResponseStatus.Unknown and not ResponseStatus.NotApplicable).Count();var missingRationale=a.Responses.Count(x=>x.Status is ResponseStatus.Unknown or ResponseStatus.NotApplicable&&string.IsNullOrWhiteSpace(x.Comment));if(incomplete>0||missingRationale>0)return Results.ValidationProblem(new Dictionary<string,string[]>{{"completion",[$"{incomplete} mandatory responses remain and {missingRationale} unknown/not-applicable responses need rationale."]}});}a.Status=i.State switch{ReviewState.Submitted=>AssessmentStatus.Submitted,ReviewState.Approved=>AssessmentStatus.Approved,ReviewState.Returned=>AssessmentStatus.Returned,_=>a.Status};a.Reviewer=u.Identity?.Name;a.ReviewComment=i.Comment;await audit.Record(db,u,i.State.ToString(),"Assessment",id,i.Comment,a.ProjectId);await db.SaveChangesAsync();return Results.Ok(a);});
api.MapGet("/evidence",async(Guid? projectId,Guid? systemId,EvidenceEntityType? entityType,Guid? entityId,AppDbContext db)=>{var q=db.Evidence.AsQueryable();if(projectId is Guid pid)q=q.Where(x=>x.ProjectId==pid);if(systemId is Guid sid)q=q.Where(x=>x.SystemId==sid);if(entityType is {} et&&entityId is Guid eid){var ids=await db.EvidenceLinks.Where(l=>!l.Archived&&l.EntityType==et&&l.EntityId==eid).Select(l=>l.EvidenceId).ToListAsync();q=q.Where(x=>ids.Contains(x.Id));}return await q.OrderByDescending(x=>x.UpdatedAt).ToListAsync();});
api.MapPost("/evidence",async(EvidenceInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u,IConfiguration config)=>{if(!Uri.TryCreate(i.Url,UriKind.Absolute,out var uri)||uri.Scheme!="https")return Results.ValidationProblem(new Dictionary<string,string[]>{{"url",["Evidence must use an HTTPS link."]}});var hosts=config.GetSection("Evidence:ApprovedHosts").Get<string[]>()??[];if(hosts.Length>0&&!hosts.Any(h=>uri.Host.Equals(h,StringComparison.OrdinalIgnoreCase)||uri.Host.EndsWith("."+h,StringComparison.OrdinalIgnoreCase)))return Results.ValidationProblem(new Dictionary<string,string[]>{{"url",["The evidence repository is not approved."]}});var e=new Evidence{ProjectId=i.ProjectId,SystemId=i.SystemId,Title=i.Title.Trim(),Url=i.Url,Source=i.Source.Trim(),Classification=i.Classification.Trim(),Validated=i.Validated,SourceType=i.SourceType,Completeness=i.Completeness,Reliability=i.Reliability,Confidentiality=i.Confidentiality,Participants=i.Participants??"",ProcessingStatus="Registered"};db.Evidence.Add(e);if(i.ResponseId is Guid responseId){var response=await db.Responses.FindAsync(responseId);if(response is null||response.ProjectId!=i.ProjectId)return Results.ValidationProblem(new Dictionary<string,string[]>{{"responseId",["The response does not belong to this project."]}});response.EvidenceLinks.Add(new ResponseEvidence{Evidence=e});}await audit.Record(db,u,"Create","Evidence",e.Id,e.Title,e.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/evidence/{e.Id}",e);});
api.MapGet("/systems/{id:guid}/integrations",async(Guid id,AppDbContext db)=>await db.Integrations.Where(x=>x.SystemId==id&&!x.Archived).ToListAsync());
api.MapPost("/systems/{id:guid}/integrations",async(Guid id,IntegrationInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var s=await db.Systems.FindAsync(id);if(s is null||s.ProjectId!=i.ProjectId)return Results.NotFound();var item=new Integration{ProjectId=i.ProjectId,SystemId=id,Name=i.Name.Trim(),Target=i.Target.Trim(),Method=i.Method.Trim(),Owner=i.Owner.Trim(),Monitoring=i.Monitoring.Trim()};if(i.CatalogId is Guid catalogId){var catalog=await db.IntegrationCatalogs.FirstOrDefaultAsync(x=>x.Id==catalogId&&!x.Archived);if(catalog is null)return Results.NotFound();IntegrationTypes.CopyFromCatalog(item,catalog);if(!string.IsNullOrWhiteSpace(i.Name))item.Name=i.Name.Trim();if(!string.IsNullOrWhiteSpace(i.Target))item.Target=i.Target.Trim();if(!string.IsNullOrWhiteSpace(i.Owner))item.Owner=i.Owner.Trim();if(!string.IsNullOrWhiteSpace(i.Method))item.Method=i.Method.Trim();}else IntegrationTypes.ApplyMapped(item,i.Method,i.IntegrationType,i.Protocol,i.DataFormat);db.Integrations.Add(item);await audit.Record(db,u,"Create","Integration",item.Id,item.Name,item.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/systems/{id}/integrations/{item.Id}",item);});
api.MapGet("/findings",async(Guid? projectId,AppDbContext db)=>await db.Findings.Where(x=>projectId==null||x.ProjectId==projectId).OrderByDescending(x=>x.Severity).ToListAsync());
api.MapPost("/findings",async(FindingInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{if(i.Severity>=Severity.High&&i.EvidenceId is null&&string.IsNullOrWhiteSpace(i.EvidenceGapRationale))return Results.ValidationProblem(new Dictionary<string,string[]>{{"evidence",["High and critical findings require evidence or an evidence-gap rationale."]}});if(i.RiskOverride is not null&&string.IsNullOrWhiteSpace(i.RiskOverrideRationale))return Results.ValidationProblem(new Dictionary<string,string[]>{{"riskOverride",["A risk override requires a rationale."]}});var f=new Finding{ProjectId=i.ProjectId,SystemId=i.SystemId,AssessmentResponseId=i.AssessmentResponseId,EvidenceId=i.EvidenceId,Type=i.Type,Title=i.Title.Trim(),Description=i.Description.Trim(),Severity=i.Severity,Likelihood=i.Likelihood,Impact=i.Impact,Owner=i.Owner.Trim(),EvidenceGapRationale=i.EvidenceGapRationale?.Trim(),RiskOverride=i.RiskOverride,RiskOverrideRationale=i.RiskOverrideRationale};db.Findings.Add(f);await audit.Record(db,u,"Create","Finding",f.Id,f.Title,f.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/findings/{f.Id}",f);});
api.MapPut("/findings/{id:guid}/review",async(Guid id,ReviewInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var f=await db.Findings.FindAsync(id);if(f is null)return Results.NotFound();f.ReviewState=i.State;f.ReviewComment=i.Comment;await audit.Record(db,u,i.State.ToString(),"Finding",id,i.Comment,f.ProjectId);await db.SaveChangesAsync();return Results.Ok(f);});
api.MapGet("/requirements",async(Guid? projectId,AppDbContext db)=>await db.Requirements.Include(x=>x.FindingLinks).Where(x=>projectId==null||x.ProjectId==projectId).ToListAsync());
api.MapPost("/requirements",async(RequirementInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{if(i.FindingIds.Count==0&&string.IsNullOrWhiteSpace(i.StandaloneRationale))return Results.ValidationProblem(new Dictionary<string,string[]>{{"traceability",["A source finding or standalone rationale is required."]}});if(await db.Findings.CountAsync(x=>i.FindingIds.Contains(x.Id)&&x.ProjectId==i.ProjectId)!=i.FindingIds.Distinct().Count())return Results.ValidationProblem(new Dictionary<string,string[]>{{"findingIds",["All source findings must belong to the requirement project."]}});var r=new Requirement{ProjectId=i.ProjectId,Title=i.Title.Trim(),Description=i.Description.Trim(),Type=i.Type.Trim(),Category=i.Category.Trim(),Priority=i.Priority,Mandatory=i.Mandatory,Rationale=i.Rationale.Trim(),AcceptanceCriteria=i.AcceptanceCriteria.Trim(),StandaloneRationale=i.StandaloneRationale?.Trim(),FindingLinks=i.FindingIds.Distinct().Select(x=>new RequirementFinding{FindingId=x}).ToList()};db.Requirements.Add(r);await audit.Record(db,u,"Create","Requirement",r.Id,r.Title,r.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/requirements/{r.Id}",r);});
api.MapPut("/requirements/{id:guid}/review",async(Guid id,ReviewInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u,IConfiguration config)=>{var r=await db.Requirements.Include(x=>x.FindingLinks).FirstOrDefaultAsync(x=>x.Id==id);if(r is null)return Results.NotFound();var actor=u.FindFirstValue(ClaimTypes.NameIdentifier)??u.Identity?.Name;if(i.State==ReviewState.Submitted)r.SubmittedBy=actor;if(i.State==ReviewState.Approved){if(r.FindingLinks.Count==0&&string.IsNullOrWhiteSpace(r.StandaloneRationale))return Results.ValidationProblem(new Dictionary<string,string[]>{{"traceability",["An approved requirement must retain a source finding or standalone rationale."]}});if(config.GetValue<bool>("Workflow:SeparationOfDuties")&&r.SubmittedBy==actor)return Results.ValidationProblem(new Dictionary<string,string[]>{{"reviewer",["The submitter cannot approve this requirement."]}});}r.ApprovalState=i.State;r.ReviewComment=i.Comment;await audit.Record(db,u,i.State.ToString(),"Requirement",id,i.Comment,r.ProjectId);await db.SaveChangesAsync();return Results.Ok(r);});

api.MapGet("/actions",async(Guid? projectId,AppDbContext db)=>await db.Actions.Where(x=>projectId==null||x.ProjectId==projectId).OrderBy(x=>x.DueDate).ToListAsync());
api.MapPost("/actions",async(ActionInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var a=new AssessmentAction{ProjectId=i.ProjectId,SystemId=i.SystemId,Title=i.Title.Trim(),Owner=i.Owner.Trim(),DueDate=i.DueDate,Priority=i.Priority};db.Actions.Add(a);await audit.Record(db,u,"Create","Action",a.Id,a.Title,a.ProjectId);await db.SaveChangesAsync();return Results.Created($"/api/actions/{a.Id}",a);});
api.MapGet("/audit",async(Guid? projectId,AppDbContext db)=>await db.AuditEvents.Where(x=>projectId==null||x.ProjectId==projectId).OrderByDescending(x=>x.Timestamp).Take(200).ToListAsync());
api.MapGet("/export/{id:guid}/{kind}",async(Guid id,string kind,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var p=await db.Projects.FindAsync(id);if(p is null)return Results.NotFound();var csv=kind.ToLowerInvariant() switch{"findings"=>Csv.Make(await db.Findings.Where(x=>x.ProjectId==id).ToListAsync(),x=>[x.Title,x.Type.ToString(),x.Severity.ToString(),x.RiskScore.ToString(),x.Owner]),"requirements"=>Csv.Make(await db.Requirements.Where(x=>x.ProjectId==id).ToListAsync(),x=>[x.Title,x.Category,x.Priority.ToString(),x.ApprovalState.ToString(),x.AcceptanceCriteria]),_=>Csv.Make(await db.Systems.Where(x=>x.ProjectId==id).ToListAsync(),x=>[x.Name,x.Acronym,x.BusinessOwner,x.TechnicalOwner,x.Criticality.ToString()])};await audit.Record(db,u,"Export","Project",id,kind,id);await db.SaveChangesAsync();return Results.File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv",$"{p.Name}-{kind}.csv");});
api.MapPost("/projects/{id:guid}/systems/batch",async(Guid id,BatchSystemsInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{if(!await db.Projects.AnyAsync(x=>x.Id==id))return Results.NotFound();var created=new List<AssessedSystem>();foreach(var item in i.Systems){var key=string.IsNullOrWhiteSpace(item.CatalogKey)?ScanWorkspace.Slug(item.Acronym,item.Name):item.CatalogKey.Trim().ToLowerInvariant();var master=await db.MasterSystems.FirstOrDefaultAsync(x=>x.CatalogKey==key||(x.Name==item.Name.Trim()&&x.Acronym==item.Acronym.Trim()));if(master is null){master=new MasterSystem{Name=item.Name.Trim(),Acronym=item.Acronym.Trim(),CatalogKey=key,Description=item.Description.Trim(),BusinessOwner=item.BusinessOwner.Trim(),TechnicalOwner=item.TechnicalOwner.Trim(),Criticality=item.Criticality,LifecycleStatus=item.Lifecycle};db.MasterSystems.Add(master);}var s=new AssessedSystem{ProjectId=id,MasterSystemId=master.Id,CatalogKey=master.CatalogKey,Name=item.Name.Trim(),Acronym=item.Acronym.Trim(),Description=item.Description.Trim(),BusinessOwner=item.BusinessOwner.Trim(),TechnicalOwner=item.TechnicalOwner.Trim(),Criticality=item.Criticality,Lifecycle=item.Lifecycle};db.Systems.Add(s);created.Add(s);await audit.Record(db,u,"Create","System",s.Id,s.Name,id);}await db.SaveChangesAsync();foreach(var s in created)await ScanWorkspace.Ensure(db,s);return Results.Created($"/api/projects/{id}/systems",created);});
api.MapGet("/assessments",async(Guid? projectId,AppDbContext db)=>{var q=db.Assessments.Include(x=>x.Responses).ThenInclude(x=>x.Question).AsQueryable();if(projectId is{}pid)q=q.Where(x=>x.ProjectId==pid);var list=await q.ToListAsync();return list.Select(a=>new{a.Id,a.ProjectId,a.SystemId,status=a.Status.ToString(),responses=a.Responses.Select(r=>new{mandatory=r.Question.Mandatory,answered=!string.IsNullOrWhiteSpace(r.Answer),status=r.Status.ToString(),confidence=r.Confidence.ToString()})});});
api.MapGet("/landscape",async(AppDbContext db)=>await db.Landscape.OrderByDescending(x=>x.CreatedAt).ToListAsync());
api.MapPost("/landscape",async(LandscapeInput i,AppDbContext db,AuditService audit,ClaimsPrincipal u)=>{var snap=new LandscapeSnapshot{Version=i.Version.Trim(),Layer=i.Layer.Trim(),Title=i.Title.Trim(),ConfirmedBy=i.ConfirmedBy.Trim(),ConfirmedAt=DateTimeOffset.UtcNow,ChangeNote=i.ChangeNote.Trim(),Document=i.Document};db.Landscape.Add(snap);await audit.Record(db,u,"Create","LandscapeSnapshot",snap.Id,$"{snap.Layer} {snap.Version}");await db.SaveChangesAsync();return Results.Created($"/api/landscape/{snap.Id}",snap);});
app.MapFallbackToFile("index.html").AllowAnonymous(); app.Run(); public partial class Program{}
