export type LandscapeCategory =
  | 'water-management'
  | 'water-monitoring'
  | 'dor-des'
  | 'external'
  | 'rural-water-futures';

export type LandscapeZone = 'internal' | 'core' | 'spatial' | 'monitoring' | 'public';

export type LandscapeSystem = {
  id: string;
  name: string;
  acronym: string;
  description: string;
  bullets: string[];
  category: LandscapeCategory;
  zone: LandscapeZone;
  x: number;
  y: number;
  w: number;
  h: number;
  regional?: boolean;
  decommissioned?: boolean;
  criticality: 'Low' | 'Moderate' | 'High' | 'Critical';
};

export type LandscapeLink = {
  from: string;
  to: string;
  label?: string;
  kind: 'data' | 'spatial' | 'payment' | 'public' | 'validation';
};

export const CANVAS = { width: 1880, height: 1160 };

export const landscapeSystems: LandscapeSystem[] = [
  {
    id: 'werd',
    name: 'Water Entitlement Registration Database',
    acronym: 'WERD',
    description: 'Historical water entitlement register. Read-only source for current accounting tools.',
    bullets: ['Historical register', 'Read only'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 52, w: 196, h: 72,
    criticality: 'Moderate',
  },
  {
    id: 'library',
    name: 'DES, DOR, DRDMW Library Services',
    acronym: 'Library',
    description: 'Departmental library catalogue used across DES, DOR and DRDMW.',
    bullets: ['Library catalogue'],
    category: 'dor-des',
    zone: 'internal',
    x: 20, y: 134, w: 196, h: 58,
    criticality: 'Low',
  },
  {
    id: 'iauditor',
    name: 'iAuditor',
    acronym: 'iAuditor',
    description: 'Regional field application used to capture meter readings, with bulk upload into CIRaM.',
    bullets: ['Field application', 'Capture meter readings'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 202, w: 196, h: 62,
    regional: true,
    criticality: 'Moderate',
  },
  {
    id: 'swan',
    name: 'SWAN Tracker',
    acronym: 'SWAN',
    description: 'Regional spreadsheet used to track seasonal water allocation notices.',
    bullets: ['Seasonal water allocation notices', 'Regional spreadsheet'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 274, w: 196, h: 62,
    regional: true,
    criticality: 'Moderate',
  },
  {
    id: 'regional-dashboards',
    name: 'Regional Dashboards and Spreadsheets',
    acronym: 'Regional BI',
    description: 'Regional Power BI and Excel dashboards used alongside core water systems.',
    bullets: ['Power BI and Excel'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 346, w: 196, h: 62,
    regional: true,
    criticality: 'Moderate',
  },
  {
    id: 'rdr',
    name: 'Regulated Dams Register',
    acronym: 'RDR',
    description: 'Register of regulated dams in the water management landscape.',
    bullets: ['Regulated dams register'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 418, w: 196, h: 54,
    criticality: 'High',
  },
  {
    id: 'wicd',
    name: 'Water Industry Compliance Database',
    acronym: 'WICD',
    description: 'Compliance database for the water industry.',
    bullets: ['Water industry compliance'],
    category: 'water-management',
    zone: 'internal',
    x: 20, y: 482, w: 196, h: 58,
    criticality: 'High',
  },
  {
    id: 'wr',
    name: 'Water Catchment Register',
    acronym: 'WR',
    description: 'Rural Water Futures catchment register.',
    bullets: ['Water catchment register'],
    category: 'rural-water-futures',
    zone: 'internal',
    x: 20, y: 550, w: 196, h: 54,
    criticality: 'High',
  },
  {
    id: 'sap',
    name: 'SAP',
    acronym: 'SAP',
    description: 'Corporate finance system receiving QWN payment postings from water customer channels.',
    bullets: ['QWN payments'],
    category: 'external',
    zone: 'internal',
    x: 20, y: 614, w: 196, h: 48,
    criticality: 'High',
  },
  {
    id: 'edocs',
    name: 'eDOCS',
    acronym: 'eDOCS',
    description: 'Corporate records management system.',
    bullets: ['Records'],
    category: 'external',
    zone: 'internal',
    x: 20, y: 672, w: 196, h: 48,
    criticality: 'Moderate',
  },
  {
    id: 'elvis',
    name: 'Elevation Information System',
    acronym: 'Elvis',
    description: 'Elevation information used to support water and vegetation monitoring.',
    bullets: ['Elevation information'],
    category: 'external',
    zone: 'core',
    x: 236, y: 52, w: 176, h: 70,
    criticality: 'Moderate',
  },
  {
    id: 'planet',
    name: 'Planet',
    acronym: 'Planet',
    description: 'Daily satellite data used to monitor water and vegetation.',
    bullets: ['Daily satellite data', 'Water and vegetation monitoring'],
    category: 'external',
    zone: 'core',
    x: 424, y: 52, w: 196, h: 70,
    criticality: 'Moderate',
  },
  {
    id: 'bom',
    name: 'Bureau of Meteorology',
    acronym: 'BOM',
    description: 'National water account, water information and water market summary feeds.',
    bullets: ['National Water Account', 'Water information', 'Water market summary'],
    category: 'external',
    zone: 'core',
    x: 640, y: 52, w: 228, h: 70,
    criticality: 'High',
  },
  {
    id: 'qspatial-live',
    name: 'QSpatial Live',
    acronym: 'QSpatial Live',
    description: 'Map-based tool presenting live spatial data into SIR and related systems.',
    bullets: ['Map-based tool with live data'],
    category: 'water-monitoring',
    zone: 'spatial',
    x: 888, y: 52, w: 188, h: 70,
    criticality: 'High',
  },
  {
    id: 'survey123',
    name: 'Survey123',
    acronym: 'Survey123',
    description: 'Field application for meter-reading capture, feeding Field Maps and spatial stores.',
    bullets: ['Field application', 'Collection to Field Maps'],
    category: 'water-monitoring',
    zone: 'spatial',
    x: 1088, y: 52, w: 196, h: 70,
    criticality: 'High',
  },
  {
    id: 'gauges',
    name: 'Water Gauges & Ground Stations',
    acronym: 'Gauges',
    description: 'Statewide gauge and station network providing time-series water and rainfall observations.',
    bullets: ['400 open surface water gauges', '180 with time-series water quality', '230 groundwater stations', '50 pluviometer rainfall stations'],
    category: 'water-monitoring',
    zone: 'monitoring',
    x: 1304, y: 52, w: 356, h: 70,
    criticality: 'Critical',
  },
  {
    id: 'mms',
    name: 'Regional Accounting Tools / MMS',
    acronym: 'MMS',
    description: 'Northern water management system covering several groundwater management areas and the water accounting tool.',
    bullets: ['Boyne, Calliope, Fitzroy, Pioneer and Whitsundays Bowen GWMA', 'Water Accounting Tool', 'Coastal Burnett Water Groundwater Management Area'],
    category: 'water-management',
    zone: 'core',
    x: 236, y: 136, w: 384, h: 96,
    regional: true,
    criticality: 'High',
  },
  {
    id: 'cat6',
    name: 'CAT6 Reporting',
    acronym: 'CAT6',
    description: 'Weekly and annual CAT6 reporting that feeds the Bureau of Meteorology.',
    bullets: ['Weekly and annual reporting'],
    category: 'water-management',
    zone: 'core',
    x: 640, y: 136, w: 108, h: 72,
    criticality: 'Moderate',
  },
  {
    id: 'ogia',
    name: 'Office of Groundwater Impact Assessment',
    acronym: 'OGIA',
    description: 'Groundwater impact assessment office, including an Azure storage container for shared datasets.',
    bullets: ['OGIA Azure Storage Container', 'Bore data and drilling records'],
    category: 'external',
    zone: 'core',
    x: 760, y: 136, w: 188, h: 72,
    criticality: 'High',
  },
  {
    id: 'sir',
    name: 'Spatial Information Resource',
    acronym: 'SIR',
    description: 'GIS repository of spatial layers including the Digital Cadastral Database.',
    bullets: ['GIS repository of spatial layers', 'Digital Cadastral Database'],
    category: 'water-monitoring',
    zone: 'spatial',
    x: 968, y: 136, w: 220, h: 86,
    criticality: 'High',
  },
  {
    id: 'sali',
    name: 'Soil and Land Information System',
    acronym: 'SALI',
    description: 'Soil and land information system exchanging laboratory data with DES LIMS.',
    bullets: ['Soil and land information'],
    category: 'dor-des',
    zone: 'monitoring',
    x: 1304, y: 136, w: 168, h: 70,
    criticality: 'Moderate',
  },
  {
    id: 'lims-des',
    name: 'Lab Information Management System',
    acronym: 'LIMS DES',
    description: 'DES laboratory information management system for H2O samples and results.',
    bullets: ['Lab info management', 'DES'],
    category: 'dor-des',
    zone: 'monitoring',
    x: 1484, y: 136, w: 176, h: 70,
    criticality: 'High',
  },
  {
    id: 'ciram',
    name: 'Compliance Information Register and Management',
    acronym: 'CIRaM',
    description: 'Compliance information register flagged for decommissioning by DLGW.',
    bullets: ['Compliance register', 'Flagged for decommissioning'],
    category: 'water-management',
    zone: 'core',
    x: 236, y: 246, w: 184, h: 72,
    regional: true,
    decommissioned: true,
    criticality: 'Low',
  },
  {
    id: 'ccms',
    name: 'Compliance Case Management System',
    acronym: 'CCMS',
    description: 'Compliance case management hosted as an Azure app with an Azure storage container.',
    bullets: ['CCMS Azure App', 'CCMS Azure Storage Container'],
    category: 'water-management',
    zone: 'core',
    x: 432, y: 246, w: 188, h: 72,
    criticality: 'High',
  },
  {
    id: 'bls',
    name: 'Bore Location System',
    acronym: 'BLS',
    description: 'Bore location register sharing data with SIR, OGIA and the groundwater database.',
    bullets: ['Bore location register'],
    category: 'water-monitoring',
    zone: 'core',
    x: 760, y: 222, w: 188, h: 58,
    criticality: 'High',
  },
  {
    id: 'spin',
    name: 'Spatial Information System',
    acronym: 'SPIN',
    description: 'Spatial query tool consuming SIR layers and groundwater datasets.',
    bullets: ['Spatial query tool'],
    category: 'water-monitoring',
    zone: 'spatial',
    x: 968, y: 234, w: 220, h: 64,
    criticality: 'High',
  },
  {
    id: 'aqeis',
    name: 'Aquatic Ecosystem Information System',
    acronym: 'AQEIS',
    description: 'Aquatic ecosystem information feeding the water analysis sample program.',
    bullets: ['Aquatic ecosystem information'],
    category: 'dor-des',
    zone: 'monitoring',
    x: 1304, y: 218, w: 168, h: 62,
    criticality: 'Moderate',
  },
  {
    id: 'lims-qh',
    name: 'Lab Information Management System',
    acronym: 'LIMS QH',
    description: 'Queensland Health laboratory information management system for H2O samples and results.',
    bullets: ['Lab info management', 'Queensland Health'],
    category: 'external',
    zone: 'monitoring',
    x: 1484, y: 218, w: 176, h: 62,
    criticality: 'High',
  },
  {
    id: 'wateriq',
    name: 'WaterIQ Manager',
    acronym: 'WaterIQ',
    description: 'Measurement and customer operations platform covering jobs, enquiries, announced allocations and reports.',
    bullets: ['Measurement management', 'Job tracker', 'Enquiry register', 'Announced allocations', 'Reports'],
    category: 'water-management',
    zone: 'core',
    x: 236, y: 330, w: 384, h: 102,
    criticality: 'Critical',
  },
  {
    id: 'gwdb',
    name: 'Groundwater Database',
    acronym: 'GWDB',
    description: 'Groundwater database with GWPlot and the Drill Log Receival and Notification system. Supports the Power BI groundwater data capture dashboard.',
    bullets: ['GWPlot (groundwater plot)', 'DRN drill log receival and notification', 'NGS data yearly; water level and quality monthly', 'Power BI groundwater dashboard'],
    category: 'water-monitoring',
    zone: 'core',
    x: 640, y: 294, w: 308, h: 118,
    criticality: 'Critical',
  },
  {
    id: 'wfieldapp',
    name: 'Water Monitoring Field Application',
    acronym: 'WFieldApp',
    description: 'Mobile field application for water monitoring, returning groundwater sample metadata and results.',
    bullets: ['Field application', 'Mobile'],
    category: 'water-monitoring',
    zone: 'spatial',
    x: 968, y: 310, w: 220, h: 70,
    criticality: 'High',
  },
  {
    id: 'wasp',
    name: 'Water Analysis Sample Program',
    acronym: 'WASP',
    description: 'Water analysis sample program supporting Power BI dashboards and feeding Hydstra and DES storage.',
    bullets: ['Sample program', 'Supports Power BI dashboards'],
    category: 'water-monitoring',
    zone: 'monitoring',
    x: 1390, y: 294, w: 200, h: 78,
    criticality: 'High',
  },
  {
    id: 'wateriq-portal',
    name: 'WaterIQ Customer Portal',
    acronym: 'WaterIQ Portal',
    description: 'Customer portal for devices, meter reads, water accounts, authorisations and works announcements.',
    bullets: ['Devices and meter reads', 'Water accounts', 'Authorisations and works announcements'],
    category: 'water-management',
    zone: 'core',
    x: 236, y: 444, w: 224, h: 88,
    criticality: 'Critical',
  },
  {
    id: 'mid',
    name: 'Australian Government Digital Identity',
    acronym: 'myID',
    description: 'Australian Government digital identity used to validate WaterIQ customer access.',
    bullets: ['ABN and identity validation'],
    category: 'external',
    zone: 'core',
    x: 472, y: 444, w: 148, h: 42,
    criticality: 'High',
  },
  {
    id: 'abr',
    name: 'Australian Business Register',
    acronym: 'ABR',
    description: 'ABN validation service for WaterIQ customer accounts.',
    bullets: ['ABN validation'],
    category: 'external',
    zone: 'core',
    x: 472, y: 490, w: 148, h: 42,
    criticality: 'Moderate',
  },
  {
    id: 'wms',
    name: 'Water Management System',
    acronym: 'WMS',
    description: 'Core water management system. Supports Power BI dashboards and exchanges title, billing and open-data extracts with ATS.',
    bullets: ['Supports Power BI dashboard', 'Title enquiries and billing', 'Open data extracts'],
    category: 'water-management',
    zone: 'core',
    x: 640, y: 426, w: 308, h: 92,
    criticality: 'Critical',
  },
  {
    id: 'des-azure',
    name: 'DES Azure Storage Container',
    acronym: 'DES Azure',
    description: 'DES Azure storage used for sample and monitoring data exchange.',
    bullets: ['Azure storage container'],
    category: 'dor-des',
    zone: 'monitoring',
    x: 1304, y: 388, w: 168, h: 58,
    criticality: 'Moderate',
  },
  {
    id: 'silo',
    name: 'SILO',
    acronym: 'SILO',
    description: 'Climate and site information service feeding the water monitoring information system.',
    bullets: ['Site information'],
    category: 'external',
    zone: 'monitoring',
    x: 1484, y: 388, w: 120, h: 58,
    criticality: 'Moderate',
  },
  {
    id: 'hcs',
    name: 'Flood Desk',
    acronym: 'HCS',
    description: 'Flood desk receiving nightly and hourly surface-water sample metadata and results.',
    bullets: ['Nightly and hourly feeds'],
    category: 'water-monitoring',
    zone: 'monitoring',
    x: 1616, y: 388, w: 144, h: 58,
    criticality: 'High',
  },
  {
    id: 'orc',
    name: 'Online Resource Capability',
    acronym: 'ORC',
    description: 'Online resource capability used for land-parcel validation and Power BI reporting.',
    bullets: ['Land parcel validation', 'Supports Power BI dashboard'],
    category: 'water-management',
    zone: 'core',
    x: 236, y: 544, w: 224, h: 78,
    criticality: 'High',
  },
  {
    id: 'gw-online',
    name: 'Groundwater Online',
    acronym: 'GW Online',
    description: 'Holding area for groundwater records exchanged with WMS and Hydstra.',
    bullets: ['Holding area', 'Bore water levels'],
    category: 'water-monitoring',
    zone: 'core',
    x: 640, y: 532, w: 188, h: 58,
    criticality: 'Moderate',
  },
  {
    id: 'hydstra',
    name: 'Water Monitoring Information System — Hydstra',
    acronym: 'WMS-Hydstra',
    description: 'Time-series data management system with Hydrotel for gauge collection and distribution.',
    bullets: ['Time-series data management', 'Hydrotel gauge collection and distribution'],
    category: 'water-monitoring',
    zone: 'monitoring',
    x: 1304, y: 460, w: 456, h: 88,
    criticality: 'Critical',
  },
  {
    id: 'bpoint',
    name: 'BPoint CommBank payment gateway',
    acronym: 'BPoint',
    description: 'Commonwealth Bank payment gateway for QWN payments from WaterIQ and Business Queensland.',
    bullets: ['QWN payments'],
    category: 'external',
    zone: 'core',
    x: 236, y: 636, w: 224, h: 64,
    criticality: 'High',
  },
  {
    id: 'ats',
    name: 'Automated Titling System',
    acronym: 'ATS',
    description: 'Automated titling system (Titles Queensland Future Fund) exchanging batch files, a realtime API and billing extracts with WMS.',
    bullets: ['Titles Queensland Future Fund', '6 batch files and realtime API', 'Billing CSV files'],
    category: 'external',
    zone: 'core',
    x: 640, y: 604, w: 308, h: 80,
    criticality: 'Critical',
  },
  {
    id: 'metering-internal',
    name: 'Metering Telemetry Internal Portal & API',
    acronym: 'Metering Internal',
    description: 'Internal metering telemetry portal and API feeding Hydstra.',
    bullets: ['Internal portal and API', 'Time-series meter reads'],
    category: 'water-monitoring',
    zone: 'monitoring',
    x: 1304, y: 562, w: 220, h: 64,
    criticality: 'High',
  },
  {
    id: 'metering-external',
    name: 'Metering Telemetry External Provider',
    acronym: 'Metering External',
    description: 'External metering telemetry provider supplying time-series meter reads.',
    bullets: ['External provider', 'Time-series meter reads'],
    category: 'external',
    zone: 'monitoring',
    x: 1540, y: 562, w: 220, h: 64,
    criticality: 'High',
  },
  {
    id: 'business-qld',
    name: 'Business Queensland',
    acronym: 'Business Qld',
    description: 'Public water entitlements, markets, announced allocations and seasonal assignment channel.',
    bullets: ['Water Entitlement Viewer (interactive map)', 'Water markets and trading reports', 'Announced entitlements and allocations', 'QWN monthly returns', 'Daily seasonal water assignment (temporary trades)'],
    category: 'water-management',
    zone: 'public',
    x: 236, y: 792, w: 340, h: 148,
    criticality: 'Critical',
  },
  {
    id: 'qspatial',
    name: 'Queensland Spatial Catalogue',
    acronym: 'QSpatial',
    description: 'Public spatial catalogue of water resource management features.',
    bullets: ['Water resource management features'],
    category: 'water-monitoring',
    zone: 'public',
    x: 592, y: 832, w: 200, h: 78,
    criticality: 'High',
  },
  {
    id: 'open-data',
    name: 'Queensland Government Open Data Portal',
    acronym: 'Open Data',
    description: 'Public open-data publication of entitlements, monitoring, border-rivers reporting and billing extracts.',
    bullets: ['Water entitlements (CSV / API)', 'Water monitoring network (XML)', 'Border Rivers WSS SWA reporting', 'Water billing (XLSX)'],
    category: 'external',
    zone: 'public',
    x: 808, y: 792, w: 248, h: 148,
    criticality: 'High',
  },
  {
    id: 'my-groundwater',
    name: 'My Groundwater Monitoring',
    acronym: 'My GW',
    description: 'Public channel for submitting bore water levels into the monitoring stack.',
    bullets: ['Submit bore water levels'],
    category: 'water-monitoring',
    zone: 'public',
    x: 1072, y: 792, w: 208, h: 64,
    criticality: 'High',
  },
  {
    id: 'geores',
    name: 'GEORES Globe',
    acronym: 'GEORES',
    description: 'Spatial presentation tool with a mining focus.',
    bullets: ['Spatial presentation tool', 'Mining focus'],
    category: 'water-monitoring',
    zone: 'public',
    x: 1072, y: 866, w: 208, h: 54,
    criticality: 'Moderate',
  },
  {
    id: 'qd-globe',
    name: 'Queensland Globe',
    acronym: 'Qld Globe',
    description: 'Public spatial presentation tool.',
    bullets: ['Spatial presentation tool'],
    category: 'water-monitoring',
    zone: 'public',
    x: 1072, y: 930, w: 208, h: 54,
    criticality: 'Moderate',
  },
  {
    id: 'wmip',
    name: 'Water Monitoring Information Portal',
    acronym: 'WMIP',
    description: 'DLGW public web portal and API for river height, stream flow, groundwater telemetry, fish-death risk and water quality.',
    bullets: ['Web portal and API', 'Current and historic river height and stream flow', 'Groundwater levels from monitoring bores', 'Monitoring sites', 'Fish death risk data', 'Water quality data'],
    category: 'water-monitoring',
    zone: 'public',
    x: 1296, y: 792, w: 364, h: 192,
    criticality: 'Critical',
  },
];

export const landscapeLinks: LandscapeLink[] = [
  { from: 'werd', to: 'mms', label: 'Data', kind: 'data' },
  { from: 'iauditor', to: 'ciram', label: 'Bulk upload', kind: 'data' },
  { from: 'wateriq', to: 'ats', label: '10s / nightly files', kind: 'data' },
  { from: 'wateriq-portal', to: 'mid', label: 'Identity', kind: 'validation' },
  { from: 'wateriq-portal', to: 'abr', label: 'ABN validation', kind: 'validation' },
  { from: 'wateriq-portal', to: 'bpoint', label: 'QWN payments', kind: 'payment' },
  { from: 'wateriq-portal', to: 'sap', label: 'QWN payments', kind: 'payment' },
  { from: 'wateriq-portal', to: 'business-qld', kind: 'public' },
  { from: 'orc', to: 'business-qld', label: 'QWN payments', kind: 'payment' },
  { from: 'orc', to: 'wms', label: 'Land parcel validation', kind: 'validation' },
  { from: 'bpoint', to: 'business-qld', label: 'QWN payment', kind: 'payment' },
  { from: 'ccms', to: 'cat6', kind: 'data' },
  { from: 'cat6', to: 'bom', kind: 'data' },
  { from: 'ogia', to: 'bom', kind: 'data' },
  { from: 'ogia', to: 'bls', kind: 'data' },
  { from: 'ogia', to: 'gwdb', label: 'Bore / drilling records', kind: 'data' },
  { from: 'qspatial-live', to: 'sir', kind: 'spatial' },
  { from: 'qspatial-live', to: 'bls', kind: 'spatial' },
  { from: 'survey123', to: 'sir', label: 'Telemetry', kind: 'spatial' },
  { from: 'survey123', to: 'qspatial-live', kind: 'spatial' },
  { from: 'sir', to: 'spin', label: 'Layers', kind: 'spatial' },
  { from: 'gauges', to: 'sir', label: 'Data feeds', kind: 'spatial' },
  { from: 'gauges', to: 'hydstra', kind: 'data' },
  { from: 'sali', to: 'lims-des', kind: 'data' },
  { from: 'lims-des', to: 'sali', kind: 'data' },
  { from: 'lims-des', to: 'wasp', label: 'H2O samples', kind: 'data' },
  { from: 'lims-qh', to: 'wasp', label: 'H2O samples', kind: 'data' },
  { from: 'aqeis', to: 'wasp', kind: 'data' },
  { from: 'wasp', to: 'des-azure', kind: 'data' },
  { from: 'wasp', to: 'hydstra', label: 'Surface water samples', kind: 'data' },
  { from: 'wfieldapp', to: 'gwdb', label: 'GW sample metadata', kind: 'data' },
  { from: 'gwdb', to: 'wms', kind: 'data' },
  { from: 'gwdb', to: 'spin', kind: 'spatial' },
  { from: 'bls', to: 'sir', kind: 'spatial' },
  { from: 'bls', to: 'gwdb', kind: 'data' },
  { from: 'wms', to: 'ats', label: 'Title enquiries / API', kind: 'validation' },
  { from: 'ats', to: 'wms', label: 'Billing CSV', kind: 'data' },
  { from: 'ats', to: 'open-data', label: 'Extracts', kind: 'public' },
  { from: 'wms', to: 'open-data', kind: 'public' },
  { from: 'wms', to: 'gw-online', kind: 'data' },
  { from: 'wms', to: 'hydstra', label: 'Feeds / reports', kind: 'data' },
  { from: 'gw-online', to: 'hydstra', label: 'Bore water levels', kind: 'data' },
  { from: 'silo', to: 'hydstra', kind: 'data' },
  { from: 'des-azure', to: 'hydstra', kind: 'data' },
  { from: 'hydstra', to: 'wmip', kind: 'public' },
  { from: 'hydstra', to: 'metering-internal', kind: 'data' },
  { from: 'metering-external', to: 'hydstra', kind: 'data' },
  { from: 'hydstra', to: 'my-groundwater', kind: 'public' },
  { from: 'my-groundwater', to: 'hydstra', label: 'Submit bore levels', kind: 'data' },
  { from: 'sir', to: 'geores', kind: 'spatial' },
  { from: 'sir', to: 'qd-globe', kind: 'spatial' },
  { from: 'business-qld', to: 'qspatial', kind: 'public' },
  { from: 'gwdb', to: 'bls', kind: 'data' },
];

export const categoryLabel: Record<LandscapeCategory, string> = {
  'water-management': 'Water management',
  'water-monitoring': 'Water monitoring',
  'dor-des': 'DOR / DES',
  external: 'External',
  'rural-water-futures': 'Rural Water Futures',
};

export function neighboursOf(id: string, links: LandscapeLink[] = landscapeLinks) {
  const inbound = links.filter(l => l.to === id);
  const outbound = links.filter(l => l.from === id);
  return { inbound, outbound, related: new Set([...inbound.map(l => l.from), ...outbound.map(l => l.to), id]) };
}

export function matchRegistered<T extends { name: string; acronym: string }>(sys: LandscapeSystem, registered: T[]) {
  const acronym = sys.acronym.trim().toLowerCase();
  const name = sys.name.trim().toLowerCase();
  return registered.find(s => {
    const a = s.acronym.trim().toLowerCase();
    const n = s.name.trim().toLowerCase();
    return (acronym && a === acronym) || n === name || (acronym && n === acronym) || (a && a === name);
  });
}
