/*
    Migration: 20260827_000_add_business_capabilities

    Purpose:
    - Add tenant-wide business capability catalog and MasterSystem coverage links.

    Notes:
    - Forward-only migration.
    - Do not edit this file after it has been applied to a shared environment.
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.BusinessCapabilities', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BusinessCapabilities
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BusinessCapabilities PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_BusinessCapabilities_Archived DEFAULT (0),
        [CatalogKey] NVARCHAR(64) NOT NULL,
        [Name] NVARCHAR(200) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [ParentId] UNIQUEIDENTIFIER NULL,
        [Level] INT NOT NULL,
        [Domain] NVARCHAR(100) NOT NULL,
        [Category] NVARCHAR(100) NOT NULL,
        [Criticality] INT NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [DefaultMaturityScore] INT NULL,
        CONSTRAINT FK_BusinessCapabilities_Parent FOREIGN KEY ([ParentId]) REFERENCES dbo.BusinessCapabilities ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_BusinessCapabilities_CatalogKey
        ON dbo.BusinessCapabilities ([CatalogKey]) WHERE [Archived] = 0;
    CREATE INDEX IX_BusinessCapabilities_ParentId ON dbo.BusinessCapabilities ([ParentId]);
END;
GO

IF OBJECT_ID(N'dbo.SystemCapabilities', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SystemCapabilities
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SystemCapabilities PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_SystemCapabilities_Archived DEFAULT (0),
        [MasterSystemId] UNIQUEIDENTIFIER NOT NULL,
        [CapabilityId] UNIQUEIDENTIFIER NOT NULL,
        [Role] INT NOT NULL,
        [MaturityScore] INT NULL,
        [Notes] NVARCHAR(MAX) NOT NULL,
        [State] INT NOT NULL,
        [Validation] INT NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        CONSTRAINT FK_SystemCapabilities_MasterSystems FOREIGN KEY ([MasterSystemId]) REFERENCES dbo.MasterSystems ([Id]) ON DELETE NO ACTION,
        CONSTRAINT FK_SystemCapabilities_BusinessCapabilities FOREIGN KEY ([CapabilityId]) REFERENCES dbo.BusinessCapabilities ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_SystemCapabilities_Master_Capability
        ON dbo.SystemCapabilities ([MasterSystemId], [CapabilityId]) WHERE [Archived] = 0;
    CREATE INDEX IX_SystemCapabilities_CapabilityId ON dbo.SystemCapabilities ([CapabilityId]);
END;
GO
