/*
    Migration: 20260901_000_add_learning_gwdb

    Purpose:
    - Add Learn GWDB course, lesson, progress, glossary, data-model and import tables.

    Notes:
    - Forward-only migration.
    - Do not edit this file after it has been applied to a shared environment.
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.LearningCourses', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningCourses
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningCourses PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningCourses_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [CatalogKey] NVARCHAR(64) NOT NULL,
        [CourseKey] NVARCHAR(200) NOT NULL,
        [Title] NVARCHAR(200) NOT NULL,
        [Description] NVARCHAR(1000) NULL,
        [Status] NVARCHAR(30) NOT NULL,
        [DisplayOrder] INT NOT NULL,
        [EstimatedMinutes] INT NOT NULL CONSTRAINT DF_LearningCourses_EstimatedMinutes DEFAULT (0),
        [Version] INT NOT NULL CONSTRAINT DF_LearningCourses_Version DEFAULT (1),
        [Tags] NVARCHAR(500) NOT NULL CONSTRAINT DF_LearningCourses_Tags DEFAULT (N''),
        CONSTRAINT FK_LearningCourses_Systems FOREIGN KEY ([SystemId]) REFERENCES dbo.Systems ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_LearningCourses_CourseKey
        ON dbo.LearningCourses ([CourseKey]) WHERE [Archived] = 0;
    CREATE INDEX IX_LearningCourses_SystemId ON dbo.LearningCourses ([SystemId]);
    CREATE INDEX IX_LearningCourses_CatalogKey ON dbo.LearningCourses ([CatalogKey]);
END;
GO

IF OBJECT_ID(N'dbo.LearningDocuments', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningDocuments
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningDocuments PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningDocuments_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [DocumentKey] NVARCHAR(200) NOT NULL,
        [Title] NVARCHAR(300) NOT NULL,
        [FileName] NVARCHAR(260) NOT NULL,
        [Version] NVARCHAR(50) NOT NULL,
        [Classification] NVARCHAR(50) NOT NULL,
        [IsAuthoritative] BIT NOT NULL CONSTRAINT DF_LearningDocuments_IsAuthoritative DEFAULT (0)
    );
    CREATE UNIQUE INDEX UX_LearningDocuments_DocumentKey
        ON dbo.LearningDocuments ([DocumentKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LearningLessons', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningLessons
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningLessons PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningLessons_Archived DEFAULT (0),
        [CourseId] UNIQUEIDENTIFIER NOT NULL,
        [LessonKey] NVARCHAR(200) NOT NULL,
        [Title] NVARCHAR(200) NOT NULL,
        [Summary] NVARCHAR(1000) NULL,
        [ContentMarkdown] NVARCHAR(MAX) NOT NULL,
        [ObjectivesJson] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LearningLessons_ObjectivesJson DEFAULT (N'[]'),
        [KeyTakeawaysJson] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LearningLessons_KeyTakeawaysJson DEFAULT (N'[]'),
        [VerificationChecksJson] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LearningLessons_VerificationChecksJson DEFAULT (N'[]'),
        [DurationMinutes] INT NULL,
        [DisplayOrder] INT NOT NULL,
        [Status] NVARCHAR(30) NOT NULL,
        [EvidenceStatus] NVARCHAR(30) NULL,
        [PublishedVersion] INT NOT NULL CONSTRAINT DF_LearningLessons_PublishedVersion DEFAULT (1),
        CONSTRAINT FK_LearningLessons_Course FOREIGN KEY ([CourseId]) REFERENCES dbo.LearningCourses ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_LearningLessons_Course_LessonKey
        ON dbo.LearningLessons ([CourseId], [LessonKey]) WHERE [Archived] = 0;
    CREATE UNIQUE INDEX UX_LearningLessons_Course_DisplayOrder
        ON dbo.LearningLessons ([CourseId], [DisplayOrder]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LessonSources', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LessonSources
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LessonSources PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LessonSources_Archived DEFAULT (0),
        [LessonId] UNIQUEIDENTIFIER NOT NULL,
        [DocumentId] UNIQUEIDENTIFIER NOT NULL,
        [PageFrom] INT NULL,
        [PageTo] INT NULL,
        [SectionName] NVARCHAR(300) NULL,
        [EvidenceStatus] NVARCHAR(30) NOT NULL,
        [SourceNote] NVARCHAR(1000) NULL,
        CONSTRAINT FK_LessonSources_Lesson FOREIGN KEY ([LessonId]) REFERENCES dbo.LearningLessons ([Id]) ON DELETE NO ACTION,
        CONSTRAINT FK_LessonSources_Document FOREIGN KEY ([DocumentId]) REFERENCES dbo.LearningDocuments ([Id]) ON DELETE NO ACTION
    );
    CREATE INDEX IX_LessonSources_LessonId ON dbo.LessonSources ([LessonId]);
END;
GO

IF OBJECT_ID(N'dbo.UserLessonProgress', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.UserLessonProgress
    (
        [UserId] NVARCHAR(200) NOT NULL,
        [LessonId] UNIQUEIDENTIFIER NOT NULL,
        [ProgressPercentage] INT NOT NULL CONSTRAINT DF_UserLessonProgress_Percentage DEFAULT (0),
        [Status] NVARCHAR(30) NOT NULL,
        [StartedAtUtc] DATETIMEOFFSET NULL,
        [LastAccessedAtUtc] DATETIMEOFFSET NULL,
        [CompletedAtUtc] DATETIMEOFFSET NULL,
        [LastPosition] NVARCHAR(200) NULL,
        CONSTRAINT PK_UserLessonProgress PRIMARY KEY ([UserId], [LessonId]),
        CONSTRAINT FK_UserLessonProgress_Lesson FOREIGN KEY ([LessonId]) REFERENCES dbo.LearningLessons ([Id]) ON DELETE NO ACTION,
        CONSTRAINT CK_UserLessonProgress_Percentage CHECK ([ProgressPercentage] BETWEEN 0 AND 100)
    );
END;
GO

IF OBJECT_ID(N'dbo.LearningBookmarks', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningBookmarks
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningBookmarks PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningBookmarks_Archived DEFAULT (0),
        [UserId] NVARCHAR(200) NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [LessonId] UNIQUEIDENTIFIER NULL,
        [EntityType] NVARCHAR(50) NULL,
        [EntityId] NVARCHAR(200) NULL,
        [Label] NVARCHAR(300) NULL,
        CONSTRAINT FK_LearningBookmarks_Lesson FOREIGN KEY ([LessonId]) REFERENCES dbo.LearningLessons ([Id]) ON DELETE NO ACTION
    );
    CREATE INDEX IX_LearningBookmarks_User_System ON dbo.LearningBookmarks ([UserId], [SystemId]);
END;
GO

IF OBJECT_ID(N'dbo.LearningNotes', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningNotes
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningNotes PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningNotes_Archived DEFAULT (0),
        [UserId] NVARCHAR(200) NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [LessonId] UNIQUEIDENTIFIER NULL,
        [EntityType] NVARCHAR(50) NULL,
        [EntityId] NVARCHAR(200) NULL,
        [NoteText] NVARCHAR(MAX) NOT NULL,
        CONSTRAINT FK_LearningNotes_Lesson FOREIGN KEY ([LessonId]) REFERENCES dbo.LearningLessons ([Id]) ON DELETE NO ACTION
    );
    CREATE INDEX IX_LearningNotes_User_System ON dbo.LearningNotes ([UserId], [SystemId]);
END;
GO

IF OBJECT_ID(N'dbo.LearningGlossaryTerms', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningGlossaryTerms
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningGlossaryTerms PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningGlossaryTerms_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [TermKey] NVARCHAR(200) NOT NULL,
        [Term] NVARCHAR(200) NOT NULL,
        [ShortDefinition] NVARCHAR(500) NOT NULL,
        [DetailedDefinition] NVARCHAR(MAX) NULL,
        [EvidenceStatus] NVARCHAR(30) NOT NULL,
        [SourceDocumentId] UNIQUEIDENTIFIER NULL,
        [SourcePage] INT NULL,
        CONSTRAINT FK_LearningGlossaryTerms_Document FOREIGN KEY ([SourceDocumentId]) REFERENCES dbo.LearningDocuments ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_LearningGlossaryTerms_System_TermKey
        ON dbo.LearningGlossaryTerms ([SystemId], [TermKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LessonQuestions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LessonQuestions
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LessonQuestions PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LessonQuestions_Archived DEFAULT (0),
        [LessonId] UNIQUEIDENTIFIER NOT NULL,
        [QuestionKey] NVARCHAR(200) NOT NULL,
        [QuestionText] NVARCHAR(1000) NOT NULL,
        [Explanation] NVARCHAR(2000) NULL,
        [DisplayOrder] INT NOT NULL,
        CONSTRAINT FK_LessonQuestions_Lesson FOREIGN KEY ([LessonId]) REFERENCES dbo.LearningLessons ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_LessonQuestions_QuestionKey
        ON dbo.LessonQuestions ([QuestionKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LessonQuestionOptions', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LessonQuestionOptions
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LessonQuestionOptions PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LessonQuestionOptions_Archived DEFAULT (0),
        [QuestionId] UNIQUEIDENTIFIER NOT NULL,
        [OptionKey] NVARCHAR(50) NOT NULL,
        [OptionText] NVARCHAR(1000) NOT NULL,
        [IsCorrect] BIT NOT NULL,
        [DisplayOrder] INT NOT NULL,
        CONSTRAINT FK_LessonQuestionOptions_Question FOREIGN KEY ([QuestionId]) REFERENCES dbo.LessonQuestions ([Id]) ON DELETE NO ACTION
    );
    CREATE INDEX IX_LessonQuestionOptions_QuestionId ON dbo.LessonQuestionOptions ([QuestionId]);
END;
GO

IF OBJECT_ID(N'dbo.LearningDataTables', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningDataTables
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningDataTables PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningDataTables_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [TableKey] NVARCHAR(200) NOT NULL,
        [Name] NVARCHAR(200) NOT NULL,
        [PhysicalName] NVARCHAR(200) NULL,
        [Description] NVARCHAR(1000) NULL,
        [Domain] NVARCHAR(100) NULL,
        [Grain] NVARCHAR(300) NULL,
        [CandidateKeyJson] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_LearningDataTables_CandidateKeyJson DEFAULT (N'[]'),
        [EvidenceStatus] NVARCHAR(30) NOT NULL
    );
    CREATE UNIQUE INDEX UX_LearningDataTables_System_TableKey
        ON dbo.LearningDataTables ([SystemId], [TableKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LearningRelationships', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningRelationships
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningRelationships PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningRelationships_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [RelationshipKey] NVARCHAR(200) NOT NULL,
        [FromTableId] UNIQUEIDENTIFIER NOT NULL,
        [ToTableId] UNIQUEIDENTIFIER NOT NULL,
        [FieldsJson] NVARCHAR(MAX) NOT NULL,
        [Cardinality] NVARCHAR(50) NOT NULL,
        [EvidenceStatus] NVARCHAR(30) NOT NULL,
        CONSTRAINT FK_LearningRelationships_FromTable FOREIGN KEY ([FromTableId]) REFERENCES dbo.LearningDataTables ([Id]) ON DELETE NO ACTION,
        CONSTRAINT FK_LearningRelationships_ToTable FOREIGN KEY ([ToTableId]) REFERENCES dbo.LearningDataTables ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_LearningRelationships_System_Key
        ON dbo.LearningRelationships ([SystemId], [RelationshipKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.LearningImports', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningImports
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningImports PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningImports_Archived DEFAULT (0),
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [PackageId] NVARCHAR(200) NOT NULL,
        [SchemaVersion] NVARCHAR(20) NOT NULL,
        [FileName] NVARCHAR(260) NOT NULL,
        [FileHash] NVARCHAR(128) NOT NULL,
        [IdempotencyKey] NVARCHAR(200) NULL,
        [Status] NVARCHAR(30) NOT NULL,
        [RequestedBy] NVARCHAR(200) NOT NULL,
        [RequestedAtUtc] DATETIMEOFFSET NOT NULL,
        [CompletedAtUtc] DATETIMEOFFSET NULL,
        [CreatedCount] INT NOT NULL CONSTRAINT DF_LearningImports_CreatedCount DEFAULT (0),
        [UpdatedCount] INT NOT NULL CONSTRAINT DF_LearningImports_UpdatedCount DEFAULT (0),
        [UnchangedCount] INT NOT NULL CONSTRAINT DF_LearningImports_UnchangedCount DEFAULT (0),
        [WarningCount] INT NOT NULL CONSTRAINT DF_LearningImports_WarningCount DEFAULT (0),
        [ErrorCount] INT NOT NULL CONSTRAINT DF_LearningImports_ErrorCount DEFAULT (0)
    );
    CREATE INDEX IX_LearningImports_SystemId ON dbo.LearningImports ([SystemId]);
    CREATE INDEX IX_LearningImports_IdempotencyKey ON dbo.LearningImports ([IdempotencyKey]);
END;
GO

IF OBJECT_ID(N'dbo.LearningImportItems', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LearningImportItems
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_LearningImportItems PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_LearningImportItems_Archived DEFAULT (0),
        [ImportId] UNIQUEIDENTIFIER NOT NULL,
        [EntityType] NVARCHAR(50) NOT NULL,
        [StableKey] NVARCHAR(200) NULL,
        [Operation] NVARCHAR(30) NOT NULL,
        [Status] NVARCHAR(30) NOT NULL,
        [JsonPath] NVARCHAR(1000) NULL,
        [ErrorCode] NVARCHAR(100) NULL,
        [Message] NVARCHAR(2000) NULL,
        CONSTRAINT FK_LearningImportItems_Import FOREIGN KEY ([ImportId]) REFERENCES dbo.LearningImports ([Id]) ON DELETE NO ACTION
    );
    CREATE INDEX IX_LearningImportItems_ImportId ON dbo.LearningImportItems ([ImportId]);
END;
GO
