/*
    Migration: 20260827_001_add_information_assets

    Purpose:
    - Add tenant-wide information asset catalog, system coverage (including SoR role),
      and capability-to-asset links.

    Notes:
    - Forward-only migration.
    - Do not edit this file after it has been applied to a shared environment.
    - System of record is SystemInformationAssets.Role only (no SoR FK on the asset).
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.InformationAssets', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.InformationAssets
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_InformationAssets PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_InformationAssets_Archived DEFAULT (0),
        [CatalogKey] NVARCHAR(64) NOT NULL,
        [Name] NVARCHAR(200) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [BusinessDefinition] NVARCHAR(MAX) NOT NULL,
        [DataOwner] NVARCHAR(MAX) NOT NULL,
        [Steward] NVARCHAR(MAX) NOT NULL,
        [Classification] INT NOT NULL,
        [RetentionPeriod] NVARCHAR(MAX) NOT NULL,
        [RegulatoryRequirements] NVARCHAR(MAX) NOT NULL,
        [Validation] INT NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL
    );
    CREATE UNIQUE INDEX UX_InformationAssets_CatalogKey
        ON dbo.InformationAssets ([CatalogKey]) WHERE [Archived] = 0;
END;
GO

IF OBJECT_ID(N'dbo.SystemInformationAssets', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SystemInformationAssets
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SystemInformationAssets PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_SystemInformationAssets_Archived DEFAULT (0),
        [MasterSystemId] UNIQUEIDENTIFIER NOT NULL,
        [InformationAssetId] UNIQUEIDENTIFIER NOT NULL,
        [Role] INT NOT NULL,
        [State] INT NOT NULL,
        [Validation] INT NOT NULL,
        [Notes] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        CONSTRAINT FK_SystemInformationAssets_MasterSystems FOREIGN KEY ([MasterSystemId]) REFERENCES dbo.MasterSystems ([Id]) ON DELETE NO ACTION,
        CONSTRAINT FK_SystemInformationAssets_InformationAssets FOREIGN KEY ([InformationAssetId]) REFERENCES dbo.InformationAssets ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_SystemInformationAssets_Master_Asset_Role
        ON dbo.SystemInformationAssets ([MasterSystemId], [InformationAssetId], [Role]) WHERE [Archived] = 0;
    CREATE UNIQUE INDEX UX_SystemInformationAssets_SoR
        ON dbo.SystemInformationAssets ([InformationAssetId]) WHERE [Role] = 0 AND [Archived] = 0;
    CREATE INDEX IX_SystemInformationAssets_InformationAssetId ON dbo.SystemInformationAssets ([InformationAssetId]);
END;
GO

IF OBJECT_ID(N'dbo.CapabilityInformationAssets', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CapabilityInformationAssets
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CapabilityInformationAssets PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_CapabilityInformationAssets_Archived DEFAULT (0),
        [CapabilityId] UNIQUEIDENTIFIER NOT NULL,
        [InformationAssetId] UNIQUEIDENTIFIER NOT NULL,
        [Notes] NVARCHAR(MAX) NOT NULL,
        CONSTRAINT FK_CapabilityInformationAssets_Capabilities FOREIGN KEY ([CapabilityId]) REFERENCES dbo.BusinessCapabilities ([Id]) ON DELETE NO ACTION,
        CONSTRAINT FK_CapabilityInformationAssets_Assets FOREIGN KEY ([InformationAssetId]) REFERENCES dbo.InformationAssets ([Id]) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX UX_CapabilityInformationAssets_Pair
        ON dbo.CapabilityInformationAssets ([CapabilityId], [InformationAssetId]) WHERE [Archived] = 0;
    CREATE INDEX IX_CapabilityInformationAssets_InformationAssetId ON dbo.CapabilityInformationAssets ([InformationAssetId]);
END;
GO
