/*
    Migration: 20260821_000_baseline_systemscope_schema

    Purpose:
    - Create the SystemScope application schema on Azure SQL.
    - Safe to run against an existing database; objects are created only if missing.

    Notes:
    - Forward-only migration.
    - Do not edit this file after it has been applied to a shared environment.
*/

SET NOCOUNT ON;
GO

IF OBJECT_ID('dbo.Projects', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Projects
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Projects PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Projects_Archived DEFAULT (0),
        [Name] NVARCHAR(MAX) NOT NULL,
        [Objective] NVARCHAR(MAX) NOT NULL,
        [Scope] NVARCHAR(MAX) NOT NULL,
        [Exclusions] NVARCHAR(MAX) NOT NULL,
        [Stakeholders] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [StartDate] DATE NOT NULL,
        [TargetDate] DATE NOT NULL,
        [Status] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.MasterSystems', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MasterSystems
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_MasterSystems PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_MasterSystems_Archived DEFAULT (0),
        [Name] NVARCHAR(MAX) NOT NULL,
        [Acronym] NVARCHAR(MAX) NOT NULL,
        [CatalogKey] NVARCHAR(MAX) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [BusinessPurpose] NVARCHAR(MAX) NOT NULL,
        [BusinessCapabilities] NVARCHAR(MAX) NOT NULL,
        [BusinessOwner] NVARCHAR(MAX) NOT NULL,
        [TechnicalOwner] NVARCHAR(MAX) NOT NULL,
        [SupportTeam] NVARCHAR(MAX) NOT NULL,
        [UserGroups] NVARCHAR(MAX) NOT NULL,
        [UserCount] INT NULL,
        [Criticality] INT NOT NULL,
        [AvailabilityExpectations] NVARCHAR(MAX) NOT NULL,
        [LifecycleStatus] NVARCHAR(MAX) NOT NULL,
        [Vendor] NVARCHAR(MAX) NOT NULL,
        [Product] NVARCHAR(MAX) NOT NULL,
        [StateClassification] INT NOT NULL,
        [Tags] NVARCHAR(MAX) NOT NULL,
        [EffectiveFrom] DATE NULL,
        [EffectiveTo] DATE NULL,
        [DataClassification] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Systems', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Systems
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Systems PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Systems_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [MasterSystemId] UNIQUEIDENTIFIER NULL,
        [CatalogKey] NVARCHAR(MAX) NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [Acronym] NVARCHAR(MAX) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [BusinessPurpose] NVARCHAR(MAX) NOT NULL,
        [BusinessCapabilities] NVARCHAR(MAX) NOT NULL,
        [BusinessOwner] NVARCHAR(MAX) NOT NULL,
        [TechnicalOwner] NVARCHAR(MAX) NOT NULL,
        [SupportTeam] NVARCHAR(MAX) NOT NULL,
        [UserGroups] NVARCHAR(MAX) NOT NULL,
        [UserCount] INT NULL,
        [AvailabilityExpectations] NVARCHAR(MAX) NOT NULL,
        [Vendor] NVARCHAR(MAX) NOT NULL,
        [Product] NVARCHAR(MAX) NOT NULL,
        [StateClassification] INT NOT NULL,
        [Tags] NVARCHAR(MAX) NOT NULL,
        [EffectiveFrom] DATE NULL,
        [EffectiveTo] DATE NULL,
        [DataClassification] NVARCHAR(MAX) NOT NULL,
        [Criticality] INT NOT NULL,
        [Lifecycle] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Templates', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Templates
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Templates PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Templates_Archived DEFAULT (0),
        [Name] NVARCHAR(MAX) NOT NULL,
        [Version] INT NOT NULL,
        [Published] BIT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Sections', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Sections
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Sections PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Sections_Archived DEFAULT (0),
        [AssessmentTemplateId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [Order] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Questions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Questions
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Questions PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Questions_Archived DEFAULT (0),
        [TemplateSectionId] UNIQUEIDENTIFIER NOT NULL,
        [Text] NVARCHAR(MAX) NOT NULL,
        [Type] INT NOT NULL,
        [Mandatory] BIT NOT NULL,
        [Order] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Assessments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Assessments
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Assessments PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Assessments_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [TemplateId] UNIQUEIDENTIFIER NOT NULL,
        [TemplateVersion] INT NOT NULL,
        [Status] INT NOT NULL,
        [Reviewer] NVARCHAR(MAX) NULL,
        [ReviewComment] NVARCHAR(MAX) NULL
    );
END;
GO

IF OBJECT_ID('dbo.Responses', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Responses
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Responses PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Responses_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessmentId] UNIQUEIDENTIFIER NOT NULL,
        [QuestionId] UNIQUEIDENTIFIER NOT NULL,
        [Answer] NVARCHAR(MAX) NULL,
        [Comment] NVARCHAR(MAX) NULL,
        [Confidence] INT NOT NULL,
        [Status] INT NOT NULL,
        [Respondent] NVARCHAR(MAX) NULL,
        [Reviewer] NVARCHAR(MAX) NULL
    );
END;
GO

IF OBJECT_ID('dbo.Evidence', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Evidence
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Evidence PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Evidence_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [Url] NVARCHAR(MAX) NOT NULL,
        [Source] NVARCHAR(MAX) NOT NULL,
        [SourceType] NVARCHAR(MAX) NOT NULL,
        [Classification] NVARCHAR(MAX) NOT NULL,
        [Validated] BIT NOT NULL,
        [Completeness] NVARCHAR(MAX) NOT NULL,
        [Reliability] NVARCHAR(MAX) NOT NULL,
        [Confidentiality] NVARCHAR(MAX) NOT NULL,
        [ProcessingStatus] NVARCHAR(MAX) NOT NULL,
        [Participants] NVARCHAR(MAX) NOT NULL,
        [EvidenceDate] DATE NULL
    );
END;
GO

IF OBJECT_ID('dbo.ResponseEvidence', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ResponseEvidence
    (
        [AssessmentResponseId] UNIQUEIDENTIFIER NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NOT NULL,
        CONSTRAINT PK_ResponseEvidence PRIMARY KEY ([AssessmentResponseId], [EvidenceId])
    );
END;
GO

IF OBJECT_ID('dbo.Integrations', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Integrations
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Integrations PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Integrations_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [SourceSystem] NVARCHAR(MAX) NOT NULL,
        [Target] NVARCHAR(MAX) NOT NULL,
        [BusinessPurpose] NVARCHAR(MAX) NOT NULL,
        [Direction] NVARCHAR(MAX) NOT NULL,
        [InformationExchanged] NVARCHAR(MAX) NOT NULL,
        [State] INT NOT NULL,
        [InterfaceType] NVARCHAR(MAX) NOT NULL,
        [Method] NVARCHAR(MAX) NOT NULL,
        [Technology] NVARCHAR(MAX) NOT NULL,
        [Frequency] NVARCHAR(MAX) NOT NULL,
        [Trigger] NVARCHAR(MAX) NOT NULL,
        [Volume] NVARCHAR(MAX) NOT NULL,
        [Authentication] NVARCHAR(MAX) NOT NULL,
        [Encryption] NVARCHAR(MAX) NOT NULL,
        [Transformation] NVARCHAR(MAX) NOT NULL,
        [ErrorHandling] NVARCHAR(MAX) NOT NULL,
        [RetryMechanism] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [Monitoring] NVARCHAR(MAX) NOT NULL,
        [Criticality] NVARCHAR(MAX) NOT NULL,
        [ReplacementImpact] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Findings', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Findings
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Findings PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Findings_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NOT NULL,
        [AssessmentResponseId] UNIQUEIDENTIFIER NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Type] INT NOT NULL,
        [Domain] INT NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [Severity] INT NOT NULL,
        [Likelihood] INT NOT NULL,
        [Impact] INT NOT NULL,
        [RiskOverride] INT NULL,
        [RiskOverrideRationale] NVARCHAR(MAX) NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [EvidenceGapRationale] NVARCHAR(MAX) NULL,
        [BusinessImpact] NVARCHAR(MAX) NOT NULL,
        [TechnicalImpact] NVARCHAR(MAX) NOT NULL,
        [Recommendation] NVARCHAR(MAX) NOT NULL,
        [Confidence] NVARCHAR(MAX) NOT NULL,
        [Validation] INT NOT NULL,
        [IncludeInDocument] BIT NOT NULL,
        [ReviewState] INT NOT NULL,
        [ReviewComment] NVARCHAR(MAX) NULL
    );
END;
GO

IF OBJECT_ID('dbo.Requirements', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Requirements
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Requirements PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Requirements_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [Type] NVARCHAR(MAX) NOT NULL,
        [Category] NVARCHAR(MAX) NOT NULL,
        [Priority] INT NOT NULL,
        [Mandatory] BIT NOT NULL,
        [Rationale] NVARCHAR(MAX) NOT NULL,
        [AcceptanceCriteria] NVARCHAR(MAX) NOT NULL,
        [StandaloneRationale] NVARCHAR(MAX) NULL,
        [ApprovalState] INT NOT NULL,
        [SubmittedBy] NVARCHAR(MAX) NULL,
        [ReviewComment] NVARCHAR(MAX) NULL
    );
END;
GO

IF OBJECT_ID('dbo.RequirementFinding', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RequirementFinding
    (
        [RequirementId] UNIQUEIDENTIFIER NOT NULL,
        [FindingId] UNIQUEIDENTIFIER NOT NULL,
        CONSTRAINT PK_RequirementFinding PRIMARY KEY ([RequirementId], [FindingId])
    );
END;
GO

IF OBJECT_ID('dbo.Actions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Actions
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Actions PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Actions_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [SystemId] UNIQUEIDENTIFIER NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [DueDate] DATE NOT NULL,
        [Priority] INT NOT NULL,
        [Status] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.AuditEvents', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AuditEvents
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AuditEvents PRIMARY KEY,
        [ProjectId] UNIQUEIDENTIFIER NULL,
        [ActorId] NVARCHAR(MAX) NOT NULL,
        [ActorName] NVARCHAR(MAX) NOT NULL,
        [Action] NVARCHAR(MAX) NOT NULL,
        [EntityType] NVARCHAR(MAX) NOT NULL,
        [EntityId] UNIQUEIDENTIFIER NOT NULL,
        [Detail] NVARCHAR(MAX) NOT NULL,
        [Timestamp] DATETIMEOFFSET NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.Landscape', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Landscape
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Landscape PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Landscape_Archived DEFAULT (0),
        [Version] NVARCHAR(MAX) NOT NULL,
        [Layer] NVARCHAR(MAX) NOT NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [ConfirmedBy] NVARCHAR(MAX) NOT NULL,
        [ConfirmedAt] DATETIMEOFFSET NULL,
        [ChangeNote] NVARCHAR(MAX) NOT NULL,
        [Document] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.ScanAssessments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ScanAssessments
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScanAssessments PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_ScanAssessments_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [MasterSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Status] INT NOT NULL,
        [IncludeInRfi] BIT NOT NULL,
        [IncludeInDocument] BIT NOT NULL,
        [Assessor] NVARCHAR(MAX) NOT NULL,
        [Reviewer] NVARCHAR(MAX) NOT NULL,
        [AssessmentLead] NVARCHAR(MAX) NOT NULL,
        [LastValidatedAt] DATETIMEOFFSET NULL,
        [LastValidatedBy] NVARCHAR(MAX) NULL,
        [InformationCompleteness] INT NOT NULL,
        [ValidationCompleteness] INT NOT NULL,
        [DocumentReadiness] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.ScanDomains', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ScanDomains
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScanDomains PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_ScanDomains_Archived DEFAULT (0),
        [ScanAssessmentId] UNIQUEIDENTIFIER NOT NULL,
        [Kind] INT NOT NULL,
        [Requirement] INT NOT NULL,
        [Summary] NVARCHAR(MAX) NOT NULL,
        [Completeness] INT NOT NULL,
        [EvidenceCount] INT NOT NULL,
        [GapCount] INT NOT NULL,
        [LastUpdatedAt] DATETIMEOFFSET NULL,
        [LastValidatedAt] DATETIMEOFFSET NULL
    );
END;
GO

IF OBJECT_ID('dbo.ScanFacts', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ScanFacts
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ScanFacts PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_ScanFacts_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Domain] INT NOT NULL,
        [Attribute] NVARCHAR(MAX) NOT NULL,
        [Value] NVARCHAR(MAX) NOT NULL,
        [Validation] INT NOT NULL,
        [ClaimType] INT NOT NULL,
        [Confidence] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [EvidenceExcerpt] NVARCHAR(MAX) NOT NULL,
        [SourceLocation] NVARCHAR(MAX) NOT NULL,
        [Visibility] INT NOT NULL,
        [State] INT NOT NULL,
        [ChangeReason] NVARCHAR(MAX) NOT NULL,
        [Speaker] NVARCHAR(MAX) NULL
    );
END;
GO

IF OBJECT_ID('dbo.Components', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Components
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Components PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Components_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [ComponentType] NVARCHAR(MAX) NOT NULL,
        [Technology] NVARCHAR(MAX) NOT NULL,
        [Version] NVARCHAR(MAX) NOT NULL,
        [Purpose] NVARCHAR(MAX) NOT NULL,
        [EnvironmentName] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [LifecycleStatus] NVARCHAR(MAX) NOT NULL,
        [SupportStatus] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.SystemDatabases', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SystemDatabases
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SystemDatabases PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_SystemDatabases_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Product] NVARCHAR(MAX) NOT NULL,
        [Edition] NVARCHAR(MAX) NOT NULL,
        [Version] NVARCHAR(MAX) NOT NULL,
        [DatabaseName] NVARCHAR(MAX) NOT NULL,
        [InstanceName] NVARCHAR(MAX) NOT NULL,
        [HostingLocation] NVARCHAR(MAX) NOT NULL,
        [OperatingSystem] NVARCHAR(MAX) NOT NULL,
        [Schemas] NVARCHAR(MAX) NOT NULL,
        [SharedOrDedicated] NVARCHAR(MAX) NOT NULL,
        [ApproximateSize] NVARCHAR(MAX) NOT NULL,
        [AnnualGrowth] NVARCHAR(MAX) NOT NULL,
        [MajorTableCount] INT NULL,
        [StoredProcedures] NVARCHAR(MAX) NOT NULL,
        [Triggers] NVARCHAR(MAX) NOT NULL,
        [DatabaseLinks] NVARCHAR(MAX) NOT NULL,
        [ScheduledJobs] NVARCHAR(MAX) NOT NULL,
        [HighAvailability] NVARCHAR(MAX) NOT NULL,
        [BackupArrangement] NVARCHAR(MAX) NOT NULL,
        [RecoveryObjectives] NVARCHAR(MAX) NOT NULL,
        [EncryptionAtRest] NVARCHAR(MAX) NOT NULL,
        [EncryptionInTransit] NVARCHAR(MAX) NOT NULL,
        [VendorSupportStatus] NVARCHAR(MAX) NOT NULL,
        [PerformanceIssues] NVARCHAR(MAX) NOT NULL,
        [TechnicalDebt] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [SupportTeam] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.InfrastructureAssets', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.InfrastructureAssets
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_InfrastructureAssets PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_InfrastructureAssets_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [AssetType] NVARCHAR(MAX) NOT NULL,
        [HostingModel] NVARCHAR(MAX) NOT NULL,
        [Location] NVARCHAR(MAX) NOT NULL,
        [OperatingSystem] NVARCHAR(MAX) NOT NULL,
        [EnvironmentName] NVARCHAR(MAX) NOT NULL,
        [NetworkZone] NVARCHAR(MAX) NOT NULL,
        [Purpose] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [EndOfLife] BIT NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.DataFlows', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DataFlows
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DataFlows PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_DataFlows_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Source] NVARCHAR(MAX) NOT NULL,
        [Destination] NVARCHAR(MAX) NOT NULL,
        [DataSet] NVARCHAR(MAX) NOT NULL,
        [BusinessPurpose] NVARCHAR(MAX) NOT NULL,
        [Direction] NVARCHAR(MAX) NOT NULL,
        [Transformation] NVARCHAR(MAX) NOT NULL,
        [StoragePoints] NVARCHAR(MAX) NOT NULL,
        [Frequency] NVARCHAR(MAX) NOT NULL,
        [SecurityClassification] NVARCHAR(MAX) NOT NULL,
        [Owner] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.BatchProcesses', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.BatchProcesses
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BatchProcesses PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_BatchProcesses_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [Purpose] NVARCHAR(MAX) NOT NULL,
        [Schedule] NVARCHAR(MAX) NOT NULL,
        [Timezone] NVARCHAR(MAX) NOT NULL,
        [UpstreamDependency] NVARCHAR(MAX) NOT NULL,
        [DownstreamDependency] NVARCHAR(MAX) NOT NULL,
        [Input] NVARCHAR(MAX) NOT NULL,
        [Output] NVARCHAR(MAX) NOT NULL,
        [RuntimeTechnology] NVARCHAR(MAX) NOT NULL,
        [TypicalDuration] NVARCHAR(MAX) NOT NULL,
        [FailureBehaviour] NVARCHAR(MAX) NOT NULL,
        [RetryProcess] NVARCHAR(MAX) NOT NULL,
        [Monitoring] NVARCHAR(MAX) NOT NULL,
        [OperationalOwner] NVARCHAR(MAX) NOT NULL,
        [Criticality] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.DataDomains', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DataDomains
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DataDomains PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_DataDomains_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [BusinessDescription] NVARCHAR(MAX) NOT NULL,
        [AuthoritativeSystem] NVARCHAR(MAX) NOT NULL,
        [PrincipalEntities] NVARCHAR(MAX) NOT NULL,
        [ApproximateVolume] NVARCHAR(MAX) NOT NULL,
        [HistoricalDepth] NVARCHAR(MAX) NOT NULL,
        [Classification] NVARCHAR(MAX) NOT NULL,
        [RetentionRequirement] NVARCHAR(MAX) NOT NULL,
        [DataOwner] NVARCHAR(MAX) NOT NULL,
        [DownstreamConsumers] NVARCHAR(MAX) NOT NULL,
        [MigrationRequirement] NVARCHAR(MAX) NOT NULL,
        [Completeness] INT NOT NULL,
        [Accuracy] INT NOT NULL,
        [Consistency] INT NOT NULL,
        [Validity] INT NOT NULL,
        [Timeliness] INT NOT NULL,
        [Uniqueness] INT NOT NULL,
        [ReferentialIntegrity] INT NOT NULL,
        [KnownDuplicates] NVARCHAR(MAX) NOT NULL,
        [MissingMandatoryValues] NVARCHAR(MAX) NOT NULL,
        [InvalidCodes] NVARCHAR(MAX) NOT NULL,
        [OrphanedRecords] NVARCHAR(MAX) NOT NULL,
        [ManualCorrectionProcess] NVARCHAR(MAX) NOT NULL,
        [ReconciliationProcess] NVARCHAR(MAX) NOT NULL,
        [QualityOwner] NVARCHAR(MAX) NOT NULL,
        [Validation] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.SecurityControls', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SecurityControls
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_SecurityControls PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_SecurityControls_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Name] NVARCHAR(MAX) NOT NULL,
        [Area] NVARCHAR(MAX) NOT NULL,
        [Description] NVARCHAR(MAX) NOT NULL,
        [Status] NVARCHAR(MAX) NOT NULL,
        [Visibility] INT NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [Validation] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.InformationGaps', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.InformationGaps
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_InformationGaps PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_InformationGaps_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Domain] INT NOT NULL,
        [MissingInformation] NVARCHAR(MAX) NOT NULL,
        [ReasonRequired] NVARCHAR(MAX) NOT NULL,
        [Priority] INT NOT NULL,
        [MarketScanImpact] NVARCHAR(MAX) NOT NULL,
        [AssignedOwner] NVARCHAR(MAX) NOT NULL,
        [DueDate] DATE NULL,
        [Status] INT NOT NULL,
        [Resolution] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL
    );
END;
GO

IF OBJECT_ID('dbo.Claims', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Claims
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Claims PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_Claims_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Domain] INT NOT NULL,
        [Statement] NVARCHAR(MAX) NOT NULL,
        [Speaker] NVARCHAR(MAX) NULL,
        [EvidenceExcerpt] NVARCHAR(MAX) NOT NULL,
        [SourceLocation] NVARCHAR(MAX) NOT NULL,
        [Confidence] NVARCHAR(MAX) NOT NULL,
        [ClaimType] INT NOT NULL,
        [Validation] INT NOT NULL,
        [AnalystDecision] NVARCHAR(MAX) NOT NULL,
        [ReviewComment] NVARCHAR(MAX) NOT NULL,
        [EvidenceId] UNIQUEIDENTIFIER NULL,
        [VisibilityLabel] NVARCHAR(MAX) NOT NULL,
        [ReviewerAssigned] NVARCHAR(MAX) NOT NULL,
        [State] INT NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.ValidationRequests', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationRequests
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ValidationRequests PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_ValidationRequests_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NOT NULL,
        [Reference] NVARCHAR(MAX) NOT NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [RequestedBy] NVARCHAR(MAX) NOT NULL,
        [Reviewer] NVARCHAR(MAX) NOT NULL,
        [DueDate] DATE NOT NULL,
        [Status] NVARCHAR(MAX) NOT NULL,
        [Context] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.ValidationItems', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ValidationItems
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ValidationItems PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_ValidationItems_Archived DEFAULT (0),
        [ValidationRequestId] UNIQUEIDENTIFIER NOT NULL,
        [ClaimId] UNIQUEIDENTIFIER NULL,
        [Domain] INT NOT NULL,
        [Statement] NVARCHAR(MAX) NOT NULL,
        [Confidence] NVARCHAR(MAX) NOT NULL,
        [Status] NVARCHAR(MAX) NOT NULL,
        [Decision] NVARCHAR(MAX) NOT NULL,
        [Comment] NVARCHAR(MAX) NOT NULL,
        [EvidenceTitle] NVARCHAR(MAX) NOT NULL,
        [EvidenceExcerpt] NVARCHAR(MAX) NOT NULL,
        [SourceLocation] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.GeneratedDocuments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GeneratedDocuments
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_GeneratedDocuments PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_GeneratedDocuments_Archived DEFAULT (0),
        [ProjectId] UNIQUEIDENTIFIER NOT NULL,
        [Title] NVARCHAR(MAX) NOT NULL,
        [TemplateName] NVARCHAR(MAX) NOT NULL,
        [TemplateVersion] NVARCHAR(MAX) NOT NULL,
        [Audience] NVARCHAR(MAX) NOT NULL,
        [StateScope] NVARCHAR(MAX) NOT NULL,
        [AssessmentVersion] NVARCHAR(MAX) NOT NULL,
        [SnapshotJson] NVARCHAR(MAX) NOT NULL,
        [FileBytes] VARBINARY(MAX) NOT NULL,
        [FileName] NVARCHAR(MAX) NOT NULL,
        [Status] NVARCHAR(MAX) NOT NULL,
        [GeneratedBy] NVARCHAR(MAX) NOT NULL,
        [IncludeDiagrams] BIT NOT NULL,
        [IncludeFindings] BIT NOT NULL,
        [IncludeGaps] BIT NOT NULL,
        [IncludeSecurityAppendix] BIT NOT NULL,
        [Warnings] NVARCHAR(MAX) NOT NULL,
        [AssessedSystemId] UNIQUEIDENTIFIER NULL,
        [CatalogKey] NVARCHAR(MAX) NOT NULL,
        [VersionLabel] NVARCHAR(MAX) NOT NULL,
        [Format] NVARCHAR(MAX) NOT NULL,
        [ApprovalState] NVARCHAR(MAX) NOT NULL,
        [Approver] NVARCHAR(MAX) NOT NULL,
        [PageCount] INT NOT NULL,
        [FileSizeBytes] INT NOT NULL,
        [Readiness] INT NOT NULL,
        [ActivityJson] NVARCHAR(MAX) NOT NULL,
        [ChecksumSha256] NVARCHAR(MAX) NOT NULL,
        [RecordId] NVARCHAR(MAX) NOT NULL,
        [Classification] NVARCHAR(MAX) NOT NULL,
        [VisibilityScope] NVARCHAR(MAX) NOT NULL,
        [PublicationNote] NVARCHAR(MAX) NOT NULL,
        [ReviewDate] DATE NULL,
        [PublishedAt] DATETIMEOFFSET NULL,
        [PublishedVersion] NVARCHAR(MAX) NOT NULL,
        [RetentionYears] INT NOT NULL,
        [SearchIndexed] BIT NOT NULL,
        [AllowDownload] BIT NOT NULL,
        [ShowOnProfile] BIT NOT NULL,
        [NotifyMembers] BIT NOT NULL,
        [AllowExternal] BIT NOT NULL,
        [Locked] BIT NOT NULL,
        [ApprovalComment] NVARCHAR(MAX) NOT NULL,
        [ApprovedAt] DATETIMEOFFSET NULL,
        [ViewCount] INT NOT NULL CONSTRAINT DF_GeneratedDocuments_ViewCount DEFAULT (0),
        [DownloadCount] INT NOT NULL CONSTRAINT DF_GeneratedDocuments_DownloadCount DEFAULT (0),
        [Summary] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.DocumentComments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DocumentComments
    (
        [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DocumentComments PRIMARY KEY,
        [CreatedAt] DATETIMEOFFSET NOT NULL,
        [UpdatedAt] DATETIMEOFFSET NOT NULL,
        [RowVersion] ROWVERSION NOT NULL,
        [Archived] BIT NOT NULL CONSTRAINT DF_DocumentComments_Archived DEFAULT (0),
        [GeneratedDocumentId] UNIQUEIDENTIFIER NOT NULL,
        [SectionNumber] INT NOT NULL,
        [Section] NVARCHAR(MAX) NOT NULL,
        [Author] NVARCHAR(MAX) NOT NULL,
        [Domain] NVARCHAR(MAX) NOT NULL,
        [Text] NVARCHAR(MAX) NOT NULL,
        [Status] NVARCHAR(MAX) NOT NULL
    );
END;
GO

IF COL_LENGTH('dbo.GeneratedDocuments', 'ViewCount') IS NULL
BEGIN
    ALTER TABLE dbo.GeneratedDocuments ADD [ViewCount] INT NOT NULL CONSTRAINT DF_GeneratedDocuments_ViewCount DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.GeneratedDocuments', 'DownloadCount') IS NULL
BEGIN
    ALTER TABLE dbo.GeneratedDocuments ADD [DownloadCount] INT NOT NULL CONSTRAINT DF_GeneratedDocuments_DownloadCount DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.GeneratedDocuments', 'Summary') IS NULL
BEGIN
    ALTER TABLE dbo.GeneratedDocuments ADD [Summary] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_GeneratedDocuments_Summary DEFAULT (N'');
END;
GO
