param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Name,

    [string]$MigrationsPath = (Join-Path $PSScriptRoot "migrations")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Name)) {
    throw "Name is required."
}

if (-not (Test-Path -LiteralPath $MigrationsPath)) {
    [void](New-Item -ItemType Directory -Path $MigrationsPath)
}

$slug = $Name.Trim().ToLowerInvariant()
$slug = [regex]::Replace($slug, "[^a-z0-9]+", "_").Trim("_")
$slug = [regex]::Replace($slug, "_{2,}", "_")

if ([string]::IsNullOrWhiteSpace($slug)) {
    throw "Name must contain at least one letter or number."
}

$date = Get-Date -Format "yyyyMMdd"
$datePattern = [regex]::Escape($date)
$maxSequence = -1

Get-ChildItem -LiteralPath $MigrationsPath -Filter ("{0}_*.sql" -f $date) |
    ForEach-Object {
        if ($_.BaseName -match "^$datePattern`_(\d{3})_") {
            $maxSequence = [Math]::Max($maxSequence, [int]$Matches[1])
        }
    }

$nextSequence = $maxSequence + 1
$migrationId = "{0}_{1:D3}_{2}" -f $date, $nextSequence, $slug
$migrationPath = Join-Path $MigrationsPath "$migrationId.sql"

if (Test-Path -LiteralPath $migrationPath) {
    throw "Migration '$migrationPath' already exists."
}

$template = @"
/*
    Migration: $migrationId

    Purpose:
    - Describe the database change.

    Notes:
    - Forward-only migration.
    - Do not edit this file after it has been applied to a shared environment.
    - Remove the placeholder THROW before running this migration.
*/

SET NOCOUNT ON;

THROW 51000, 'Migration $migrationId has not been implemented yet. Replace this placeholder with SQL changes.', 1;
GO

-- Example guarded schema change:
-- IF COL_LENGTH('dbo.ExampleTable', 'NewColumn') IS NULL
-- BEGIN
--     ALTER TABLE dbo.ExampleTable
--         ADD NewColumn NVARCHAR(100) NULL;
-- END;
-- GO
"@

Set-Content -LiteralPath $migrationPath -Value $template -Encoding UTF8
Write-Host "Created migration $migrationPath"
